Repository TusharKesarwani/Front-End-Projects, pull requests merged in 2023-02, with the labels that each got.

#538 Step Progress bar
  Projects/step-progress-bar/Readme.md
  Projects/step-progress-bar/index.html
  Projects/step-progress-bar/script.js
  Projects/step-progress-bar/styles.css
Labels: Beginner, SWOC 3.0

#372 Add Quote Generator
  Projects/Quote Generator/README.md
  Projects/Quote Generator/index.html
  Projects/Quote Generator/quotes.js
  Projects/Quote Generator/script.js
  Projects/Quote Generator/style.css
Labels: Beginner, SWOC 3.0

#535 Space Tourism Website #534
  Projects/Space Tourism Website/destination.html
  Projects/Space Tourism Website/img/astronaut.webp
  Projects/Space Tourism Website/img/astronaut2.webp
  Projects/Space Tourism Website/img/bg-1.jpg
  Projects/Space Tourism Website/img/bg-2.jpg
  Projects/Space Tourism Website/img/earth.png
  Projects/Space Tourism Website/img/europa.webp
  Projects/Space Tourism Website/img/favicon.svg
  Projects/Space Tourism Website/img/mars.webp
  Projects/Space Tourism Website/img/moon.webp
  Projects/Space Tourism Website/img/titan.webp
  Projects/Space Tourism Website/index.html
  Projects/Space Tourism Website/index.js
  Projects/Space Tourism Website/readme.md
  Projects/Space Tourism Website/style.css
  Projects/Space Tourism Website/style1.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#540 Corona-Tracker
  Projects/Corona-Tracker/README.md
  Projects/Corona-Tracker/index.css
  Projects/Corona-Tracker/index.html
  Projects/Corona-Tracker/index.js
  Projects/Corona-Tracker/index.php
  Projects/Corona-Tracker/m.jpg
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#524 A Drawing App-Sketch It #106
  Projects/DRAWING APP/1675012499654_SketchIt.jpg
  Projects/DRAWING APP/Readme.md
  Projects/DRAWING APP/drawing .png
  Projects/DRAWING APP/icons/brush.svg
  Projects/DRAWING APP/icons/circle.svg
  Projects/DRAWING APP/icons/eraser.svg
  Projects/DRAWING APP/icons/rectangle.svg
  Projects/DRAWING APP/icons/triangle.svg
  Projects/DRAWING APP/landing .png
  Projects/DRAWING APP/landing.css
  Projects/DRAWING APP/landing.html
  Projects/DRAWING APP/sketch.css
  Projects/DRAWING APP/sketch.html
  Projects/DRAWING APP/sketch.js
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#542 Movie Data Base
  Projects/MovieDataBase/MovieDataBase.html
  Projects/MovieDataBase/MovieDataBaseCss.css
  Projects/MovieDataBase/MovieDataBaseJs.js
  Projects/MovieDataBase/README.md
  Projects/MovieDataBase/Screenshot 2023-01-31 004839.png
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#573 ReactionTimeApp Files
  Projects/Reaction_App/README.md
  Projects/Reaction_App/index.html
  Projects/Reaction_App/main.js
  Projects/Reaction_App/style.css
Labels: enhancement, Approved, Medium, Ready to merge, SWOC 3.0

#575 Crypto DashBoard
  Projects/Crypto Dashboard/README.md
  Projects/Crypto Dashboard/assets/about-banner.png
  Projects/Crypto Dashboard/assets/app-banner.png
  Projects/Crypto Dashboard/assets/appstore.png
  Projects/Crypto Dashboard/assets/chart-1.svg
  Projects/Crypto Dashboard/assets/chart-2.svg
  Projects/Crypto Dashboard/assets/coin-1.svg
  Projects/Crypto Dashboard/assets/coin-2.svg
  Projects/Crypto Dashboard/assets/coin-3.svg
  Projects/Crypto Dashboard/assets/coin-4.svg
  Projects/Crypto Dashboard/assets/coin-5.svg
  Projects/Crypto Dashboard/assets/coin-6.svg
  Projects/Crypto Dashboard/assets/coin-7.svg
  Projects/Crypto Dashboard/assets/coin-8.svg
  Projects/Crypto Dashboard/assets/connect-line.png
  Projects/Crypto Dashboard/assets/googleplay.png
  Projects/Crypto Dashboard/assets/hero-banner.png
  Projects/Crypto Dashboard/assets/instruction-1.png
  Projects/Crypto Dashboard/assets/instruction-2.png
  Projects/Crypto Dashboard/assets/instruction-3.png
  Projects/Crypto Dashboard/assets/instruction-4.png
  Projects/Crypto Dashboard/assets/logo.svg
  Projects/Crypto Dashboard/favicon.svg
  Projects/Crypto Dashboard/index.html
  Projects/Crypto Dashboard/script.js
  Projects/Crypto Dashboard/style.css
Labels: Advanced, Ready to merge, SWOC 3.0

#577 Educational website
  Projects/Education Website/README.md
  Projects/Education Website/about.html
  Projects/Education Website/contact.html
  Projects/Education Website/courses.html
  Projects/Education Website/css/about.css
  Projects/Education Website/css/contact.css
  Projects/Education Website/css/style.css
  Projects/Education Website/images/about achievements.svg
  Projects/Education Website/images/avatar1.jpg
  Projects/Education Website/images/avatar2.jpg
  Projects/Education Website/images/avatar3.jpg
  Projects/Education Website/images/avatar4.jpg
  Projects/Education Website/images/avatar5.jpg
  Projects/Education Website/images/avatar6.jpg
  Projects/Education Website/images/avatar7.jpg
  Projects/Education Website/images/background texture.psd
  Projects/Education Website/images/bg-texture.png
  Projects/Education Website/images/contact.svg
  Projects/Education Website/images/course1.jpg
  Projects/Education Website/images/course10.jpg
  Projects/Education Website/images/course11.jpg
  Projects/Education Website/images/course12.jpg
  Projects/Education Website/images/course13.jpg
  Projects/Education Website/images/course14.jpg
  Projects/Education Website/images/course15.jpg
  Projects/Education Website/images/course16.jpg
  Projects/Education Website/images/course17.jpg
  Projects/Education Website/images/course18.jpg
  Projects/Education Website/images/course2.jpg
  Projects/Education Website/images/course3.jpg
  Projects/Education Website/images/course4.jpg
  Projects/Education Website/images/course5.jpg
  Projects/Education Website/images/course6.jpg
  Projects/Education Website/images/course7.jpg
  Projects/Education Website/images/course8.jpg
  Projects/Education Website/images/course9.jpg
  Projects/Education Website/images/header.svg
  Projects/Education Website/images/tm1.jpg
  Projects/Education Website/images/tm10.jpg
  Projects/Education Website/images/tm2.jpg
  Projects/Education Website/images/tm3.jpg
  Projects/Education Website/images/tm4.jpg
  Projects/Education Website/images/tm5.jpg
  Projects/Education Website/images/tm6.jpg
  Projects/Education Website/images/tm7.jpg
  Projects/Education Website/images/tm8.jpg
  Projects/Education Website/images/tm9.jpg
  Projects/Education Website/index.html
  Projects/Education Website/main.js
Labels: Approved, Advanced, Ready to merge, SWOC 3.0

#569 donation website with payment gateway integration
  Projects/Donation-Website/README.md
  Projects/Donation-Website/images/bg3.jpg
  Projects/Donation-Website/images/finalllogo.jpg
  Projects/Donation-Website/images/int.jpg
  Projects/Donation-Website/images/int2.jpg
  Projects/Donation-Website/images/int3.jpg
  Projects/Donation-Website/index.html
  Projects/Donation-Website/resp.js
  Projects/Donation-Website/style.css
Labels: bug, SWOC 3.0

#581 Quotes
  Projects/Quote Generator/README.md
  Projects/Quote Generator/index.html
  Projects/Quote Generator/script.js
  Projects/Quote Generator/style.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#571 Restaurant Website
  Projects/Restaurant-website/Info.html
  Projects/Restaurant-website/Menu.html
  Projects/Restaurant-website/README.md
  Projects/Restaurant-website/css/styles.css
  Projects/Restaurant-website/homepage.html
  Projects/Restaurant-website/images/coffee.png
  Projects/Restaurant-website/images/loading.gif
  Projects/Restaurant-website/images/logo.png
  Projects/Restaurant-website/images/soda.png
  Projects/Restaurant-website/images/ss1.png
  Projects/Restaurant-website/images/ss2.png
  Projects/Restaurant-website/images/ss3.png
  Projects/Restaurant-website/index.html
  Projects/Restaurant-website/js/jquery-3.6.0.js
  Projects/Restaurant-website/js/script.js
  Projects/Restaurant-website/specific.html
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#584 added Bookmark app
  Projects/Bookmarker_App/README.md
  Projects/Bookmarker_App/index.html
  Projects/Bookmarker_App/logo.svg
  Projects/Bookmarker_App/main.js
  Projects/Bookmarker_App/style.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#499 Added Flipkart Clone Project
  Projects/Flipkart clone/Readme.md
  Projects/Flipkart clone/cart.png
  Projects/Flipkart clone/cloneStyle.css
  Projects/Flipkart clone/flipkart.png
  Projects/Flipkart clone/flipkartCloneProject.html
  Projects/Flipkart clone/mixer.png
  Projects/Flipkart clone/search.png
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#594 Postman Clone
  Projects/Postman Clone/Readme.md
  Projects/Postman Clone/index.html
  Projects/Postman Clone/script.js
  Projects/Postman Clone/styles.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#601 Web chat
  Projects/Web-Chat/components/active-chat.js
  Projects/Web-Chat/components/app-brand.js
  Projects/Web-Chat/components/authed-user.js
  Projects/Web-Chat/components/chat-box.js
  Projects/Web-Chat/components/chat-list-item.js
  Projects/Web-Chat/components/chat-message.js
  Projects/Web-Chat/components/chats-list.js
  Projects/Web-Chat/components/component.js
  Projects/Web-Chat/components/new-message.js
  Projects/Web-Chat/index.html
  Projects/Web-Chat/readme.md
  Projects/Web-Chat/scripts/chat-app.js
  Projects/Web-Chat/scripts/data-factory.js
  Projects/Web-Chat/scripts/index.js
  Projects/Web-Chat/scripts/recorder.js
  Projects/Web-Chat/static/chat-box-bg.png
  Projects/Web-Chat/static/chat-placeholder.svg
  Projects/Web-Chat/static/mic.svg
  Projects/Web-Chat/styles/styles.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#602 Modern credi Card form Webpage
  Projects/Modern credit Card form Webpage/README.md
  Projects/Modern credit Card form Webpage/Screenshot 2023-01-31 232214.jpg
  Projects/Modern credit Card form Webpage/index.css
  Projects/Modern credit Card form Webpage/index.html
  Projects/Modern credit Card form Webpage/script.js
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#603 Sanskrit Quiz App Files
  Projects/Sans/README.md
  Projects/Sans/app.css
  Projects/Sans/end.html
  Projects/Sans/end.js
  Projects/Sans/game.css
  Projects/Sans/game.html
  Projects/Sans/game.js
  Projects/Sans/highscores.css
  Projects/Sans/highscores.html
  Projects/Sans/highscores.js
  Projects/Sans/index.html
  Projects/Sans/result.html
Labels: Approved, Ready to merge, SWOC 3.0

#612 Ballon Popping Game
  Projects/BALLON POPPING GAME/Readme.md
  Projects/BALLON POPPING GAME/index.html
  Projects/BALLON POPPING GAME/script.js
  Projects/BALLON POPPING GAME/style.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#617 Save text as file
  Projects/Save Text as File/index.html
  Projects/Save Text as File/readme.md
  Projects/Save Text as File/script.js
  Projects/Save Text as File/style.css
Labels: Assigned, Approved, Medium, SWOC 3.0

#632 Breathe meditation Website
  Projects/Breathe Meditation/README.md
  Projects/Breathe Meditation/index.html
  Projects/Breathe Meditation/script.js
  Projects/Breathe Meditation/style.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#637 image slider project
  Projects/image slider/1000_F_110664347_nvuQnGVJ7Cx2i43YYiK8NU9aKKjtaKBD.jpg
  Projects/image slider/1000_F_237757770_Idjb882cpeBrvCgg2OQNcnhAPW6dXHrg.jpg
  Projects/image slider/1000_F_258180661_y40ddZDL7IxNK5LuPqXZTPOcbSv08t4x.jpg
  Projects/image slider/1000_F_276548042_gy7eqXvwv0uVirBVIiRHvLw0rpOOci59.jpg
  Projects/image slider/1000_F_295098064_bNPd09kftGLtWtzpecaz87aonSeXO0Bp.jpg
  Projects/image slider/1000_F_85904537_no3STjliVLgPaTQZZcUi0QytodzicxvF.jpg
  Projects/image slider/1000_F_95987109_I6EF6m8O0DWc8pdQXGvQau1e2oZcS6wa.jpg
  Projects/image slider/Readme.md
  Projects/image slider/cute-corgi-sitting-couch_23-2148865700.jpg
  Projects/image slider/cute-dog-with-party-hat-couch_23-2148865701.jpg
  Projects/image slider/index.html
  Projects/image slider/script.js
  Projects/image slider/side-view-cute-dog-bathtub-outdoors_23-2149658807.jpg
  Projects/image slider/style.css
Labels: Approved, Beginner, SWOC 3.0

#635 Sorting Visualizer
  Projects/Sorting Visualizer/README.MD
  Projects/Sorting Visualizer/bubble.js
  Projects/Sorting Visualizer/count.js
  Projects/Sorting Visualizer/home.js
  Projects/Sorting Visualizer/index.html
  Projects/Sorting Visualizer/insertion.js
  Projects/Sorting Visualizer/merge.js
  Projects/Sorting Visualizer/my-style.css
  Projects/Sorting Visualizer/quick.js
  Projects/Sorting Visualizer/styles_900px.css
Labels: Medium, SWOC 3.0

#641 Hoolix - Agency website
  Projects/hoolix-digital agency website/README.md
  Projects/hoolix-digital agency website/assets/css/style.css
  Projects/hoolix-digital agency website/assets/images/about-banner.png
  Projects/hoolix-digital agency website/assets/images/hero-banner.png
  Projects/hoolix-digital agency website/assets/images/hero-pattern.svg
  Projects/hoolix-digital agency website/assets/images/service-1.png
  Projects/hoolix-digital agency website/assets/images/service-2.png
  Projects/hoolix-digital agency website/assets/images/service-3.png
  Projects/hoolix-digital agency website/assets/images/service-4.png
  Projects/hoolix-digital agency website/assets/js/script.js
  Projects/hoolix-digital agency website/favicon.svg
  Projects/hoolix-digital agency website/index.html
  Projects/hoolix-digital agency website/readme-images/desktop.png
Labels: Medium, SWOC 3.0

#659 excel clone
  Projects/Excel clone/README.md
  Projects/Excel clone/formula.js
  Projects/Excel clone/fx.png
  Projects/Excel clone/index.html
  Projects/Excel clone/init.js
  Projects/Excel clone/menu.js
  Projects/Excel clone/nos.js
  Projects/Excel clone/sheets.js
  Projects/Excel clone/style.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#660 Doclab - website for hospital
  Projects/Doclab/assets/css/style.css
  Projects/Doclab/assets/images/Thumbs.db
  Projects/Doclab/assets/images/about-banner.png
  Projects/Doclab/assets/images/blog-card.jpg
  Projects/Doclab/assets/images/footer-bg.png
  Projects/Doclab/assets/images/hero-banner.png
  Projects/Doclab/assets/images/hero-bg.png
  Projects/Doclab/assets/images/icon-1.png
  Projects/Doclab/assets/images/icon-2.png
  Projects/Doclab/assets/images/icon-3.png
  Projects/Doclab/assets/images/icon-4.png
  Projects/Doclab/assets/images/icon-5.png
  Projects/Doclab/assets/images/icon-6.png
  Projects/Doclab/assets/images/icon-7.png
  Projects/Doclab/assets/images/logo.svg
  Projects/Doclab/assets/js/script.js
  Projects/Doclab/favicon.svg
  Projects/Doclab/index.html
  Projects/Doclab/readme.md
Labels: Approved, Medium, Ready to merge, SWOC 3.0
