Repository TusharKesarwani/Front-End-Projects, pull requests merged in 2023-01, with the labels that each got.

#13 Cool Website Elements
  Projects/Animated Card/animated_card.css
  Projects/Animated Card/animated_card.html
  Projects/Expanding Card Design/expending_card_design.css
  Projects/Expanding Card Design/expending_card_design.html
  Projects/Expanding Card Design/expending_card_design.js
  Projects/FAQ Page/faq_page.css
  Projects/FAQ Page/faq_page.html
  Projects/Hidden Search/hidden_search.css
  Projects/Hidden Search/hidden_search.html
  Projects/Hidden Search/hidden_search.js
  Projects/Loading/loading.css
  Projects/Loading/loading.html
  Projects/Loading/loading.js
Labels: Medium, SWOC 3.0

#14 updated the web application of jaguar car for front-end projects
  Projects/Jaguar Car Website/images/Jaguar-logo.jpg
  Projects/Jaguar Car Website/images/c1.jpg
  Projects/Jaguar Car Website/images/c2.jfif
  Projects/Jaguar Car Website/images/c3.jfif
  Projects/Jaguar Car Website/images/c4.jfif
  Projects/Jaguar Car Website/images/c5.jfif
  Projects/Jaguar Car Website/images/car1.jpg
  Projects/Jaguar Car Website/images/car2.jpg
  Projects/Jaguar Car Website/images/car3.jpg
  Projects/Jaguar Car Website/images/car4.jpeg
  Projects/Jaguar Car Website/images/car5.webp
  Projects/Jaguar Car Website/images/car6.jpg
  Projects/Jaguar Car Website/images/car7.jpg
  Projects/Jaguar Car Website/images/display.jpg
  Projects/Jaguar Car Website/images/display1.jfif
  Projects/Jaguar Car Website/images/display1.jpg
  Projects/Jaguar Car Website/images/display2.jpg
  Projects/Jaguar Car Website/images/display3.jpg
  Projects/Jaguar Car Website/images/display4.jpg
  Projects/Jaguar Car Website/images/display5.jpg
  Projects/Jaguar Car Website/images/display6.jpg
  Projects/Jaguar Car Website/images/display6.webp
  Projects/Jaguar Car Website/images/display7.jpeg
  Projects/Jaguar Car Website/images/display7.jpg
  Projects/Jaguar Car Website/images/display8.jpg
  Projects/Jaguar Car Website/images/display8.webp
  Projects/Jaguar Car Website/images/jaguar-xf.png
  Projects/Jaguar Car Website/images/pexels-mike-b-192501.jpg
  Projects/Jaguar Car Website/images/wp2803080-jaguar-cars-wallpaper-desktop.jpg
  Projects/Jaguar Car Website/index.html
  Projects/Jaguar Car Website/script.js
  Projects/Jaguar Car Website/style1.css
  Projects/Jaguar Car Website/style2.css
  Projects/Jaguar Car Website/style3.css
Labels: Medium, SWOC 3.0

#18 Tindog website (Issue #7)
  Projects/TinDog Website/README.md
  Projects/TinDog Website/css/styles.css
  Projects/TinDog Website/images/TechCrunch.png
  Projects/TinDog Website/images/bizinsider.png
  Projects/TinDog Website/images/dog-img.jpg
  Projects/TinDog Website/images/iphone6.png
  Projects/TinDog Website/images/lady-img.jpg
  Projects/TinDog Website/images/mashable.png
  Projects/TinDog Website/images/tnw.png
  Projects/TinDog Website/index.html
  img/projects/tindog_website1.png
  index.html
Labels: Medium, SWOC 3.0

#36 Ping Pong Game
  Projects/Ping-Png/700.css
  Projects/Ping-Png/Paddle.js
  Projects/Ping-Png/README.md
  Projects/Ping-Png/app.js
  Projects/Ping-Png/ball.js
  Projects/Ping-Png/index.html
  Projects/Ping-Png/style.css
Labels: Medium, SWOC 3.0

#37 Weather-Website
  Projects/Weather/Readme.md
  Projects/Weather/index.html
  Projects/Weather/info.txt
  Projects/Weather/script.js
Labels: Medium, SWOC 3.0

#40 Added Product Card made using HTML, CSS and JS
  Projects/boAt-Product-Card/assets/boAt-Logo.png
  Projects/boAt-Product-Card/assets/cod.png
  Projects/boAt-Product-Card/assets/credit-card.png
  Projects/boAt-Product-Card/assets/headphone01.png
  Projects/boAt-Product-Card/assets/headphone02.png
  Projects/boAt-Product-Card/assets/headphone03.png
  Projects/boAt-Product-Card/assets/headphone04.png
  Projects/boAt-Product-Card/assets/headphone05-model.png
  Projects/boAt-Product-Card/assets/headphone06.png
  Projects/boAt-Product-Card/assets/headphone07.png
  Projects/boAt-Product-Card/assets/paytm.png
  Projects/boAt-Product-Card/assets/star.png
  Projects/boAt-Product-Card/assets/zest-logo.svg
  Projects/boAt-Product-Card/index.html
  Projects/boAt-Product-Card/script.js
  Projects/boAt-Product-Card/style.css
Labels: Beginner, SWOC 3.0

#35 Palindrome_cheacker
  Projects/palindrome/palindrome.JPG
  Projects/palindrome/palindrome.css
  Projects/palindrome/palindrome.html
  Projects/palindrome/palindrome.js
Labels: Beginner, SWOC 3.0

#41 Drum Player and Dice-Game Project
  Projects/Dice project/Readme.md
  Projects/Dice project/dicee.html
  Projects/Dice project/images/dice1.png
  Projects/Dice project/images/dice2.png
  Projects/Dice project/images/dice3.png
  Projects/Dice project/images/dice4.png
  Projects/Dice project/images/dice5.png
  Projects/Dice project/images/dice6.png
  Projects/Dice project/index.js
  Projects/Dice project/styles.css
  Projects/Drum Kit Starting Files/images/crash.png
  Projects/Drum Kit Starting Files/images/kick.png
  Projects/Drum Kit Starting Files/images/snare.png
  Projects/Drum Kit Starting Files/images/tom1.png
  Projects/Drum Kit Starting Files/images/tom2.png
  Projects/Drum Kit Starting Files/images/tom3.png
  Projects/Drum Kit Starting Files/images/tom4.png
  Projects/Drum Kit Starting Files/index.html
  Projects/Drum Kit Starting Files/index.js
  Projects/Drum Kit Starting Files/sounds/crash.mp3
  Projects/Drum Kit Starting Files/sounds/kick-bass.mp3
  Projects/Drum Kit Starting Files/sounds/snare.mp3
  Projects/Drum Kit Starting Files/sounds/tom-1.mp3
  Projects/Drum Kit Starting Files/sounds/tom-2.mp3
  Projects/Drum Kit Starting Files/sounds/tom-3.mp3
  Projects/Drum Kit Starting Files/sounds/tom-4.mp3
  Projects/Drum Kit Starting Files/styles.css
Labels: Medium, SWOC 3.0

#46 text-utils-react-app
  Projects/Text-Utils/.gitignore
  Projects/Text-Utils/package-lock.json
  Projects/Text-Utils/package.json
  Projects/Text-Utils/public/favicon-16x16.png
  Projects/Text-Utils/public/favicon-32x32.png
  Projects/Text-Utils/public/favicon.ico
  Projects/Text-Utils/public/index.html
  Projects/Text-Utils/public/manifest.json
  Projects/Text-Utils/public/robots.txt
  Projects/Text-Utils/src/App.css
  Projects/Text-Utils/src/App.js
  Projects/Text-Utils/src/App.test.js
  Projects/Text-Utils/src/components/About.js
  Projects/Text-Utils/src/components/Alert.js
  Projects/Text-Utils/src/components/Navbar.js
  Projects/Text-Utils/src/components/Textform.js
  Projects/Text-Utils/src/index.css
  Projects/Text-Utils/src/index.js
  Projects/Text-Utils/src/logo.svg
  Projects/Text-Utils/src/reportWebVitals.js
  Projects/Text-Utils/src/setupTests.js
  img/projects/Text-utils.jpg
Labels: Medium, SWOC 3.0

#47 Tic-tac-toe project added
  Projects/TIC-TAC-TOE PROJECT/0.gif
  Projects/TIC-TAC-TOE PROJECT/600.css
  Projects/TIC-TAC-TOE PROJECT/X.gif
  Projects/TIC-TAC-TOE PROJECT/bg1.jpg
  Projects/TIC-TAC-TOE PROJECT/index.html
  Projects/TIC-TAC-TOE PROJECT/index.js
  Projects/TIC-TAC-TOE PROJECT/styles.css
  Projects/TIC-TAC-TOE PROJECT/xo.png
Labels: Medium, SWOC 3.0

#48 Added BMI Calculator
  Projects/BMICalculator/assets/healthy.jpg
  Projects/BMICalculator/assets/obese.jpg
  Projects/BMICalculator/assets/overweight.jpg
  Projects/BMICalculator/assets/underweight.jpg
  Projects/BMICalculator/index.html
  Projects/BMICalculator/scripts.js
  Projects/BMICalculator/style.css
Labels: Medium, SWOC 3.0

#64 added Temperature Converter Project
  Projects/Temperatureconverter/index.html
  Projects/Temperatureconverter/style.css
Labels: Beginner, SWOC 3.0

#65 the great drum kit project added for SWOC
  Projects/The Great Drumkit/README.md
  Projects/The Great Drumkit/index.html
  Projects/The Great Drumkit/resources/images/nainoa-shizuru-NcdG9mK3PBY-unsplash.jpg
  Projects/The Great Drumkit/script.js
  Projects/The Great Drumkit/sounds/boom.wav
  Projects/The Great Drumkit/sounds/clap.wav
  Projects/The Great Drumkit/sounds/hihat.wav
  Projects/The Great Drumkit/sounds/kick.wav
  Projects/The Great Drumkit/sounds/openhat.wav
  Projects/The Great Drumkit/sounds/ride.wav
  Projects/The Great Drumkit/sounds/snare.wav
  Projects/The Great Drumkit/sounds/tink.wav
  Projects/The Great Drumkit/sounds/tom.wav
  Projects/The Great Drumkit/styles.css
Labels: Beginner, SWOC 3.0

#68 Stopwatch-by Vanshika
  Projects/stopwatch/Stopwatch.html
  Projects/stopwatch/style.css
Labels: Medium, SWOC 3.0

#83 Password Generator
  Projects/Password Generator/index.html
  Projects/Password Generator/script.js
  Projects/Password Generator/style.css
Labels: Medium, SWOC 3.0

#77 Drink Water Record App
  Projects/DrinkWaterReminderApplication/index.html
  Projects/DrinkWaterReminderApplication/script.js
  Projects/DrinkWaterReminderApplication/style.css
Labels: Beginner, SWOC 3.0

#67 Tripocity
  Projects/Tripocity/index.html
  Projects/Tripocity/pages/Bhopal1.html
  Projects/Tripocity/pages/Gwalior1.html
  Projects/Tripocity/pages/MagicalMandu1.html
  Projects/Tripocity/pages/Orchha1.html
  Projects/Tripocity/pages/Pachmari1.html
  Projects/Tripocity/pages/TripocityReviews1.html
  Projects/Tripocity/pages/Ujjain1.html
  Projects/Tripocity/pages/aboutus1.html
  Projects/Tripocity/pages/amarkantak1.html
  Projects/Tripocity/pages/bandhavgarh1.html
  Projects/Tripocity/pages/bhimbetka1.html
  Projects/Tripocity/pages/indore1.html
  Projects/Tripocity/pages/jabalpur1.html
  Projects/Tripocity/pages/kanha1.html
  Projects/Tripocity/pages/khajuraho1.html
  Projects/Tripocity/pages/panna1.html
  Projects/Tripocity/pages/sanchi1.html
  Projects/Tripocity/pages/seasons1.html
  Projects/Tripocity/pages/shivpuri1.html
  Projects/Tripocity/pages/tamia1.html
  Projects/Tripocity/style/nav.css
  Projects/Tripocity/style/season1.css
  Projects/Tripocity/style/style_tripocity1.css
Labels: Medium, SWOC 3.0

#70 Adding Food Ordering Website #15
  Projects/Food Ordering website/image/100377.jpg
  Projects/Food Ordering website/image/1PUB_Desktop_Deals-v1_1168x520.jpg
  Projects/Food Ordering website/image/1PUB_McDelivery_v4_1168x520.jpg
  Projects/Food Ordering website/image/Screenshot 2023-01-05 112116.jpg
  Projects/Food Ordering website/image/Screenshot 2023-01-05 113325.jpg
  Projects/Food Ordering website/image/Screenshot 2023-01-05 113544.jpg
  Projects/Food Ordering website/image/TwoPub_Desktop_NutritionCalculator_1110x740_2-column-desktop.jpeg
  Projects/Food Ordering website/image/Variety_2Col_1110x740_Desktop_2-column-desktop.jpeg
  Projects/Food Ordering website/image/bg-about.png
  Projects/Food Ordering website/image/detail.txt
  Projects/Food Ordering website/image/download (1).png
  Projects/Food Ordering website/image/download (2).png
  Projects/Food Ordering website/image/download (3).png
  Projects/Food Ordering website/image/download.jpeg
  Projects/Food Ordering website/image/download.png
  Projects/Food Ordering website/image/download1.jpeg
  Projects/Food Ordering website/image/images (1).jpeg
  Projects/Food Ordering website/image/images (2).jpeg
  Projects/Food Ordering website/image/images.jpeg
  Projects/Food Ordering website/image/instagram-icon_1057-2227.jpg
  Projects/Food Ordering website/image/logo.png
  Projects/Food Ordering website/image/what-is-musha-musha.png
  Projects/Food Ordering website/index.html
  Projects/Food Ordering website/style.css
Labels: Beginner, SWOC 3.0

#88 Google Drive Clone
  Projects/Google Drive Clone/Google-Drive-Clone-main/README.md
  Projects/Google Drive Clone/Google-Drive-Clone-main/index.html
  Projects/Google Drive Clone/Google-Drive-Clone-main/style.css
Labels: Beginner, SWOC 3.0

#89 TaskList website
  Projects/TaskList/app.js
  Projects/TaskList/bg.png
  Projects/TaskList/close1.png
  Projects/TaskList/favicon.ico
  Projects/TaskList/index.html
  Projects/TaskList/style.css
Labels: Beginner, SWOC 3.0

#119 Added Github Profile Finder Project(Issue number : 17)
  Projects/Github Profile Wrapper/UI.js
  Projects/Github Profile Wrapper/bg.png
  Projects/Github Profile Wrapper/index.html
  Projects/Github Profile Wrapper/script.js
  Projects/Github Profile Wrapper/style.css
Labels: Medium, SWOC 3.0

#120 Dictionary webapp using pure html,css,js and rapid api
  Projects/Dictionary_WebApp/index.html
  Projects/Dictionary_WebApp/script.js
  Projects/Dictionary_WebApp/source/android-icon-192x192.png
  Projects/Dictionary_WebApp/style.css
Labels: Medium, SWOC 3.0

#146 Whack A Mole
  Projects/Whack-A-Mole/images/Background.jpg
  Projects/Whack-A-Mole/images/diglet.png
  Projects/Whack-A-Mole/index.html
  Projects/Whack-A-Mole/script.js
  Projects/Whack-A-Mole/style.css
Labels: Medium, Ready to merge, SWOC 3.0

#141 armstrong checker
  Projects/ArmstrongChecker/armstrong.css
  Projects/ArmstrongChecker/armstrong.html
  Projects/ArmstrongChecker/armstrong.js
Labels: Beginner, SWOC 3.0

#136 screen recording website
  Projects/screen recording website/code.js
  Projects/screen recording website/index.html
  Projects/screen recording website/style.css
Labels: Medium, SWOC 3.0

#135 Made a simple music player
  Projects/Music Player/bg1.jpg
  Projects/Music Player/music.css
  Projects/Music Player/music.html
  Projects/Music Player/zara zara.jpg
  Projects/Music Player/zara zara.mp3
Labels: Beginner, Ready to merge, SWOC 3.0

#96 The Hangman Game added
  Projects/The-Hangman-Game/LICENSE
  Projects/The-Hangman-Game/confirmationWindow.js
  Projects/The-Hangman-Game/images/1.png
  Projects/The-Hangman-Game/images/2.png
  Projects/The-Hangman-Game/images/3.png
  Projects/The-Hangman-Game/images/4.png
  Projects/The-Hangman-Game/images/5.png
  Projects/The-Hangman-Game/images/6.png
  Projects/The-Hangman-Game/images/7.png
  Projects/The-Hangman-Game/images/hangmanLogo.png
  Projects/The-Hangman-Game/index.html
  Projects/The-Hangman-Game/index.js
  Projects/The-Hangman-Game/styles.css
  Projects/The-Hangman-Game/words.json
  img/projects/The-Hangman-Game.jpg
  index.html
Labels: Medium, SWOC 3.0

#94 A Well Designed Analog Clock added (Issue Number 33)
  Projects/Analog Clock/BeFunky-photo.jpg
  Projects/Analog Clock/index.html
  Projects/Analog Clock/script.js
  Projects/Analog Clock/style.css
Labels: Beginner, SWOC 3.0

#103 Usability clone has been added /project
  Projects/UsabilitHub/assets/asset 0.png
  Projects/UsabilitHub/assets/asset 1.png
  Projects/UsabilitHub/assets/asset 10.svg
  Projects/UsabilitHub/assets/asset 11.svg
  Projects/UsabilitHub/assets/asset 12.svg
  Projects/UsabilitHub/assets/asset 13.svg
  Projects/UsabilitHub/assets/asset 14.svg
  Projects/UsabilitHub/assets/asset 15.svg
  Projects/UsabilitHub/assets/asset 16.svg
  Projects/UsabilitHub/assets/asset 17.svg
  Projects/UsabilitHub/assets/asset 18.png
  Projects/UsabilitHub/assets/asset 19.png
  Projects/UsabilitHub/assets/asset 2.png
  Projects/UsabilitHub/assets/asset 20.png
  Projects/UsabilitHub/assets/asset 21.png
  Projects/UsabilitHub/assets/asset 22.png
  Projects/UsabilitHub/assets/asset 23.png
  Projects/UsabilitHub/assets/asset 24.png
  Projects/UsabilitHub/assets/asset 25.png
  Projects/UsabilitHub/assets/asset 26.png
  Projects/UsabilitHub/assets/asset 27.svg
  Projects/UsabilitHub/assets/asset 28.png
  Projects/UsabilitHub/assets/asset 29.png
  Projects/UsabilitHub/assets/asset 3.png
  Projects/UsabilitHub/assets/asset 30.png
  Projects/UsabilitHub/assets/asset 31.png
  Projects/UsabilitHub/assets/asset 32.png
  Projects/UsabilitHub/assets/asset 33.svg
  Projects/UsabilitHub/assets/asset 34.svg
  Projects/UsabilitHub/assets/asset 35.svg
  Projects/UsabilitHub/assets/asset 36.jpeg
  Projects/UsabilitHub/assets/asset 37.jpeg
  Projects/UsabilitHub/assets/asset 38.jpeg
  Projects/UsabilitHub/assets/asset 39.jpeg
  Projects/UsabilitHub/assets/asset 4.png
  Projects/UsabilitHub/assets/asset 40.png
  Projects/UsabilitHub/assets/asset 41.png
  Projects/UsabilitHub/assets/asset 5.png
  Projects/UsabilitHub/assets/asset 6.png
  Projects/UsabilitHub/assets/asset 7.png
  Projects/UsabilitHub/assets/asset 8.svg
  Projects/UsabilitHub/assets/asset 9.png
  Projects/UsabilitHub/index.html
  Projects/UsabilitHub/media-queries.css
  Projects/UsabilitHub/style.css
Labels: Beginner, SWOC 3.0

#111 adding signin page to Front-End-Projects
  Projects/SignIn Page/css/style.css
  Projects/SignIn Page/index.html
  Projects/SignIn Page/js/app.js
Labels: Beginner, SWOC 3.0

#123 adding timer project
  Projects/Timer/index.css
  Projects/Timer/index.html
  Projects/Timer/index.js
Labels: Beginner, Ready to merge, SWOC 3.0

#131 Stone, paper & scissor game (issue #52)
  Projects/stone paper game/img/paper.png
  Projects/stone paper game/img/robot.png
  Projects/stone paper game/img/rock.png
  Projects/stone paper game/img/scissor.png
  Projects/stone paper game/index.css
  Projects/stone paper game/index.html
  Projects/stone paper game/index.js
Labels: Beginner, Ready to merge, SWOC 3.0

#104 Added Shades Landing page
  Projects/Shades/assets/1st.jpg
  Projects/Shades/assets/2nd.jpg
  Projects/Shades/assets/3rd.jpg
  Projects/Shades/assets/Project_143-16.jpg
  Projects/Shades/assets/demo.png
  Projects/Shades/assets/home-page.png
  Projects/Shades/assets/laptop.png
  Projects/Shades/assets/layer-group-solid.svg
  Projects/Shades/assets/template.png
  Projects/Shades/index.html
  Projects/Shades/styles.css
Labels: Medium, SWOC 3.0

#154 Pig game has been added successfully
  Projects/Pig game/Readme.md
  Projects/Pig game/dice-1.png
  Projects/Pig game/dice-2.png
  Projects/Pig game/dice-3.png
  Projects/Pig game/dice-4.png
  Projects/Pig game/dice-5.png
  Projects/Pig game/dice-6.png
  Projects/Pig game/index.html
  Projects/Pig game/pig-game-flowchart.png
  Projects/Pig game/pig1.png
  Projects/Pig game/pig2.png
  Projects/Pig game/script.js
  Projects/Pig game/style.css
Labels: Medium, Ready to merge, SWOC 3.0

#157 Day Planner Website
  Projects/Day Planner/README.md
  Projects/Day Planner/index.html
  Projects/Day Planner/javascript.js
  Projects/Day Planner/style.css
Labels: Ready to merge, SWOC 3.0

#162 number guessing game using JS
  Projects/number_guessing_game/code.js
  Projects/number_guessing_game/index.html
  Projects/number_guessing_game/readme.md
  Projects/number_guessing_game/style.css
Labels: Beginner, Ready to merge, SWOC 3.0

#163 QR Code Generator
  Projects/QR Code Generator/Index.html
  Projects/QR Code Generator/README.md
  Projects/QR Code Generator/ScreenShot_QR Code Generator.jpg
  Projects/QR Code Generator/script.js
  Projects/QR Code Generator/style.css
Labels: Beginner, Ready to merge, SWOC 3.0

#174 Hex code
  Projects/Hex Code Generator/Readme.md
  Projects/Hex Code Generator/Screenshot (222).png
  Projects/Hex Code Generator/index.html
  Projects/Hex Code Generator/script.js
  Projects/Hex Code Generator/style.css
Labels: Medium, Ready to merge, SWOC 3.0

#180 added the code for random meme generator
  Projects/Meme Generator/README.md
  Projects/Meme Generator/Screenshot 2023-01-10 at 8.24.15 PM.png
  Projects/Meme Generator/index.html
  Projects/Meme Generator/main.js
  Projects/Meme Generator/style.css
Labels: Approved, Beginner, SWOC 3.0

#183 Age calculator using javascript
  Projects/Age calculator/index.html
  Projects/Age calculator/readme.md
  Projects/Age calculator/script.js
  Projects/Age calculator/style.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#220 Visit Counter #204
  Projects/Visit Counter/README.md
  Projects/Visit Counter/index.html
  Projects/Visit Counter/script.js
  Projects/Visit Counter/style.css
Labels: Medium, Ready to merge, SWOC 3.0

#221 Removed dead links from website homepage
  index.html
Labels: Beginner, Ready to merge, SWOC 3.0

#187 Whiteboard with Color Selection and Saving feature
  Projects/WhiteBoard/README.md
  Projects/WhiteBoard/images/Preview.png
  Projects/WhiteBoard/index.html
  Projects/WhiteBoard/script.js
  Projects/WhiteBoard/style.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#198 Feat #86 dictionary
  Projects/dictionary/README.md
  Projects/dictionary/index.html
  Projects/dictionary/script.js
  Projects/dictionary/style.css
Labels: Beginner, Ready to merge, SWOC 3.0

#202 GYM WEB
  Projects/Gym-Website/README.md
  Projects/Gym-Website/css/animate.css
  Projects/Gym-Website/css/style.css
  Projects/Gym-Website/images/about1.jpg
  Projects/Gym-Website/images/about2.jpg
  Projects/Gym-Website/images/about3.jpg
  Projects/Gym-Website/images/class1.jpg
  Projects/Gym-Website/images/class2.png
  Projects/Gym-Website/images/gallery1.jpg
  Projects/Gym-Website/images/gallery2.jpg
  Projects/Gym-Website/images/gallery3.jpg
  Projects/Gym-Website/images/gallery4.jpg
  Projects/Gym-Website/images/home.jpg
  Projects/Gym-Website/images/price1.jpg
  Projects/Gym-Website/images/price2.jpg
  Projects/Gym-Website/images/price3.jpg
  Projects/Gym-Website/images/schedule1.png
  Projects/Gym-Website/index.html
  Projects/Gym-Website/min.js
Labels: Medium, Ready to merge, SWOC 3.0

#255 Virtual keyboard added
  Projects/Virtual Keyboard/app.js
  Projects/Virtual Keyboard/index.html
  Projects/Virtual Keyboard/pagestyle.css
  Projects/Virtual Keyboard/readme.md
  Projects/Virtual Keyboard/styles.css
Labels: Beginner, Ready to merge, SWOC 3.0

#251 Digital Clock #205
  Projects/Digital Clock/README.md
  Projects/Digital Clock/index.html
  Projects/Digital Clock/script.js
  Projects/Digital Clock/style.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#266 Typing speed checker
  Projects/Typing Speed Game/images/image2.jpg
  Projects/Typing Speed Game/images/readme.md
  Projects/Typing Speed Game/index.html
  Projects/Typing Speed Game/js/paragraph.js
  Projects/Typing Speed Game/js/readme.md
  Projects/Typing Speed Game/js/script.js
  Projects/Typing Speed Game/readme.md
  Projects/Typing Speed Game/style.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#308 Chess game clone
  Projects/chess/Bbishop.png
  Projects/chess/Bking.png
  Projects/chess/Bknight.png
  Projects/chess/Bpawn.png
  Projects/chess/Bqueen.png
  Projects/chess/Brook.png
  Projects/chess/Wbishop.png
  Projects/chess/Wking.png
  Projects/chess/Wknight.png
  Projects/chess/Wpawn.png
  Projects/chess/Wqueen.png
  Projects/chess/Wrook.png
  Projects/chess/code.js
  Projects/chess/index.html
  Projects/chess/readme.md
  Projects/chess/style.css
Labels: Approved, Ready to merge, SWOC 3.0

#307 Added Contributors list #295
  index.html
  style.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#292 OTP Verification #279
  Projects/OTP Verification/Readme.md
  Projects/OTP Verification/css/form.css
  Projects/OTP Verification/css/index.css
  Projects/OTP Verification/css/verify.css
  Projects/OTP Verification/home.html
  Projects/OTP Verification/login.html
  Projects/OTP Verification/signup.html
  Projects/OTP Verification/verify.html
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#281 FAVICON FETCHER (ISSUE NUMBER : #260)
  Projects/Favicon Fetcher/README.md
  Projects/Favicon Fetcher/images/icon.png
  Projects/Favicon Fetcher/index.html
  Projects/Favicon Fetcher/script.js
  Projects/Favicon Fetcher/styles.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#273 added calendar
  Projects/Calendar/img.png
  Projects/Calendar/index.html
  Projects/Calendar/readme.md
  Projects/Calendar/script.js
  Projects/Calendar/styles.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#261 Added e-commerce landing page
  Projects/E-commerce Landing Page/images/Ellipse 6.png
  Projects/E-commerce Landing Page/images/Gal-Gadot.jpg
  Projects/E-commerce Landing Page/images/Group 2.png
  Projects/E-commerce Landing Page/images/Group 424.png
  Projects/E-commerce Landing Page/images/Group 425.png
  Projects/E-commerce Landing Page/images/Group 426.png
  Projects/E-commerce Landing Page/images/Group 427.png
  Projects/E-commerce Landing Page/images/Hetart.png
  Projects/E-commerce Landing Page/images/JY7z8NP.png
  Projects/E-commerce Landing Page/images/NoPath - Copy (10).png
  Projects/E-commerce Landing Page/images/NoPath - Copy (11).png
  Projects/E-commerce Landing Page/images/NoPath - Copy (12).png
  Projects/E-commerce Landing Page/images/NoPath - Copy (13).png
  Projects/E-commerce Landing Page/images/NoPath - Copy (2).png
  Projects/E-commerce Landing Page/images/NoPath - Copy (6).png
  Projects/E-commerce Landing Page/images/NoPath - Copy (7).png
  Projects/E-commerce Landing Page/images/NoPath - Copy (8).png
  Projects/E-commerce Landing Page/images/NoPath - Copy (9).png
  Projects/E-commerce Landing Page/images/NoPath - Copy.png
  Projects/E-commerce Landing Page/images/NoPath.png
  Projects/E-commerce Landing Page/images/Reshot-by-Shikhil-Sharma.png
  Projects/E-commerce Landing Page/images/adult-blue-casual-1503009.png
  Projects/E-commerce Landing Page/images/bajaj-original.jpeg
  Projects/E-commerce Landing Page/images/bat.jpeg
  Projects/E-commerce Landing Page/images/bell-53.png
  Projects/E-commerce Landing Page/images/blur-close-up-depth-of-field-1478442.png
  Projects/E-commerce Landing Page/images/cart-simple.png
  Projects/E-commerce Landing Page/images/for-you-shelf.png
  Projects/E-commerce Landing Page/images/heart-2.png
  Projects/E-commerce Landing Page/images/oneplus.png
  Projects/E-commerce Landing Page/images/shopping-bag.png
  Projects/E-commerce Landing Page/images/slider-btn-1.png
  Projects/E-commerce Landing Page/images/slider-btn.png
  Projects/E-commerce Landing Page/images/young-man-dressed-up.png
  Projects/E-commerce Landing Page/index.html
  Projects/E-commerce Landing Page/readme.md
  Projects/E-commerce Landing Page/styles.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#326 Image editor
  Projects/image editor/code.js
  Projects/image editor/image-placeholder.svg
  Projects/image editor/index.html
  Projects/image editor/readme.md
  Projects/image editor/style.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#310 Added Animation in the floating boy and improved hover feature in Cards.
  style.css
Labels: Beginner, SWOC 3.0

#210 Developer profile branch
  Projects/Developer  Profile card/Photos/Photo1.jpg
  Projects/Developer  Profile card/Photos/Screenshot (229).png
  Projects/Developer  Profile card/Readme.md
  Projects/Developer  Profile card/all.css
  Projects/Developer  Profile card/index.html
  Projects/Developer  Profile card/style.css
Labels: Beginner, SWOC 3.0

#238 Add files via upload
  Projects/Theme Switcher/README.md
  Projects/Theme Switcher/screenshot.jpg
  Projects/Theme Switcher/switch_theme.html
  Projects/Theme Switcher/switch_theme_css.css
  Projects/Theme Switcher/switch_theme_js.js
Labels: Beginner, SWOC 3.0

#340 Added Zomato Landing Page
  Projects/Zomato-Landing-Page/README.md
  Projects/Zomato-Landing-Page/images/appleStore.png
  Projects/Zomato-Landing-Page/images/collection1.jpg
  Projects/Zomato-Landing-Page/images/collection2.jpg
  Projects/Zomato-Landing-Page/images/collection3.jpg
  Projects/Zomato-Landing-Page/images/collection4.jpg
  Projects/Zomato-Landing-Page/images/heroSectionBackground.png
  Projects/Zomato-Landing-Page/images/heroSectionLogo.png
  Projects/Zomato-Landing-Page/images/item1.png
  Projects/Zomato-Landing-Page/images/item2.png
  Projects/Zomato-Landing-Page/images/item3.png
  Projects/Zomato-Landing-Page/images/item4.png
  Projects/Zomato-Landing-Page/images/logo.png
  Projects/Zomato-Landing-Page/images/mobileBanner.png
  Projects/Zomato-Landing-Page/images/playStore.png
  Projects/Zomato-Landing-Page/index.html
  Projects/Zomato-Landing-Page/styles.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#343 Brick Breaker Game
  Projects/Brick Breaker Game/Readme.md
  Projects/Brick Breaker Game/game.css
  Projects/Brick Breaker Game/game.html
  Projects/Brick Breaker Game/game.js
  Projects/Brick Breaker Game/image/screenshot.png
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#347 pincode checker
  Projects/Pincode checker/Readme.md
  Projects/Pincode checker/img.png
  Projects/Pincode checker/index.html
  Projects/Pincode checker/script.js
  Projects/Pincode checker/styles.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#354 Bookmarker application
  Projects/Bookmarker_App/README.md
  Projects/Bookmarker_App/bootstrap.min.css
  Projects/Bookmarker_App/bootstrap.min.js
  Projects/Bookmarker_App/index.html
  Projects/Bookmarker_App/main.js
  Projects/Bookmarker_App/style.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#356 Audio_to_text conversion
  Projects/Audio-Text-Converter/README.md
  Projects/Audio-Text-Converter/index.html
  Projects/Audio-Text-Converter/script.js
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#283 Added Language Translator Project
  Projects/Langugaetranslator/Readme.Md
  Projects/Langugaetranslator/country.js
  Projects/Langugaetranslator/index.html
  Projects/Langugaetranslator/script.js
  Projects/Langugaetranslator/style.css
Labels: Beginner, SWOC 3.0

#230 Memory Game (4 Tiles)
  Projects/Memory Game/README.md
  Projects/Memory Game/game.js
  Projects/Memory Game/index.html
  Projects/Memory Game/sounds/blue.mp3
  Projects/Memory Game/sounds/green.mp3
  Projects/Memory Game/sounds/red.mp3
  Projects/Memory Game/sounds/wrong.mp3
  Projects/Memory Game/sounds/yellow.mp3
  Projects/Memory Game/styles.css
Labels: enhancement

#318 Added Magic-Ball folder
  Projects/Magic-balls/Readme.md
  Projects/Magic-balls/index.html
  Projects/Magic-balls/photo.png
  Projects/Magic-balls/script.js
  Projects/Magic-balls/style.css
Labels: Beginner, Ready to merge, SWOC 3.0

#366 Connect4 game using HTML ,CSS and JAVASCRIPT
  Projects/connect4 game/code.js
  Projects/connect4 game/index.html
  Projects/connect4 game/readme.md
  Projects/connect4 game/style.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#385 Recipe finder
  Projects/Recipe Finder/README.md
  Projects/Recipe Finder/assets/script.js
  Projects/Recipe Finder/assets/scroll.css
  Projects/Recipe Finder/assets/style.css
  Projects/Recipe Finder/index.html
Labels: Approved, Ready to merge, SWOC 3.0

#404 Login page 3 d
  Projects/3D Login Page/Images/Screenshot (259).png
  Projects/3D Login Page/Images/Screenshot (260).png
  Projects/3D Login Page/Images/bg.png
  Projects/3D Login Page/Readme.md
  Projects/3D Login Page/index.html
  Projects/3D Login Page/script.js
  Projects/3D Login Page/style.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#425 Truth table generator
  Projects/truth table generator/index.html
  Projects/truth table generator/jquery.js
  Projects/truth table generator/qunit.css
  Projects/truth table generator/qunit.js
  Projects/truth table generator/readme.md
  Projects/truth table generator/test.html
  Projects/truth table generator/test.js
  Projects/truth table generator/truth.css
  Projects/truth table generator/truth.js
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#396 Dynamic js quiz
  Projects/Dynamic js Quiz/README.md
  Projects/Dynamic js Quiz/index.html
  Projects/Dynamic js Quiz/style.css
  Projects/Dynamic js Quiz/text.js
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#410 added Emoji Rating project
  Projects/Emoji Rating/README.md
  Projects/Emoji Rating/emoji rating.png
  Projects/Emoji Rating/index.html
  Projects/Emoji Rating/index.js
  Projects/Emoji Rating/style.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#432 Atmosphere air quality app
  Projects/Air-Quality/README.md
  Projects/Air-Quality/index.html
  Projects/Air-Quality/script.js
  Projects/Air-Quality/style.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#436 Added Gooey cursor
  Projects/Gooey Cursor/Readme.md
  Projects/Gooey Cursor/img1.png
  Projects/Gooey Cursor/img2.png
  Projects/Gooey Cursor/index.html
  Projects/Gooey Cursor/javascript.js
  Projects/Gooey Cursor/style.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#461 SpaceX Website Clone
  Projects/SpaceX-Clone/README.md
  Projects/SpaceX-Clone/css/style.css
  Projects/SpaceX-Clone/dragon.html
  Projects/SpaceX-Clone/falcon-heavy.html
  Projects/SpaceX-Clone/falcon9.html
  Projects/SpaceX-Clone/img/dragon.webp
  Projects/SpaceX-Clone/img/falcon-9.webp
  Projects/SpaceX-Clone/img/falcon-heavy.webp
  Projects/SpaceX-Clone/img/logo.png
  Projects/SpaceX-Clone/img/screen.jpg
  Projects/SpaceX-Clone/img/section-a.webp
  Projects/SpaceX-Clone/img/section-b.webp
  Projects/SpaceX-Clone/img/section-c.webp
  Projects/SpaceX-Clone/img/section-d.webp
  Projects/SpaceX-Clone/img/section-e.webp
  Projects/SpaceX-Clone/img/section-f.webp
  Projects/SpaceX-Clone/index.html
  Projects/SpaceX-Clone/js/script.js
Labels: Approved, Advanced, Ready to merge, SWOC 3.0

#462 Loan-Calculator
  Projects/Loan-calculator/README.md
  Projects/Loan-calculator/index.html
  Projects/Loan-calculator/loancalculator.css
  Projects/Loan-calculator/loancalculator.js
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#466 Adding Color Selection Option in hexcode Generator
  Projects/Hex Code Generator/Readme.md
  Projects/Hex Code Generator/index.html
  Projects/Hex Code Generator/script.js
  Projects/Hex Code Generator/style.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#472 Tourism addition
  Projects/Tourism/README.md
  Projects/Tourism/images/B1.jpg
  Projects/Tourism/images/H1.jfif
  Projects/Tourism/images/H2.jpg
  Projects/Tourism/images/H3.jfif
  Projects/Tourism/images/H4.jpg
  Projects/Tourism/images/H5.jpg
  Projects/Tourism/images/H6.jpg
  Projects/Tourism/images/I1.jpg
  Projects/Tourism/images/I2.jpg
  Projects/Tourism/images/I3.jfif
  Projects/Tourism/images/I3.jpg
  Projects/Tourism/images/I4.jpg
  Projects/Tourism/images/I5.jpg
  Projects/Tourism/images/K1.jpg
  Projects/Tourism/images/K2.jpg
  Projects/Tourism/images/K3.jpg
  Projects/Tourism/images/K4.jpg
  Projects/Tourism/images/S1.jpg
  Projects/Tourism/images/S2.jpg
  Projects/Tourism/images/S3.jpg
  Projects/Tourism/images/app_store.png
  Projects/Tourism/images/banner.jpg
  Projects/Tourism/images/britain.jpg
  Projects/Tourism/images/logo.png
  Projects/Tourism/images/play_store.png
  Projects/Tourism/images/subscribe.png
  Projects/Tourism/index.html
  Projects/Tourism/style.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#484 Ball ninja game
  Projects/Ball Ninja Game/index.html
  Projects/Ball Ninja Game/readme.md
  Projects/Ball Ninja Game/script.js
  Projects/Ball Ninja Game/sound/Sword_Sound_Effects/Sword-swipe-1.wav
  Projects/Ball Ninja Game/sound/Sword_Sound_Effects/Sword-swipe-2.wav
  Projects/Ball Ninja Game/sound/Sword_Sound_Effects/Sword-swipe-3.wav
  Projects/Ball Ninja Game/sound/Sword_Sound_Effects/Sword-swipe-4.wav
  Projects/Ball Ninja Game/sound/Sword_Sound_Effects/Sword-swipe-5.wav
  Projects/Ball Ninja Game/sound/Sword_Sound_Effects/Sword-swipe-6.wav
  Projects/Ball Ninja Game/sound/Sword_Sound_Effects/Sword-swipe-7.wav
  Projects/Ball Ninja Game/sound/gank.wav
  Projects/Ball Ninja Game/sound/ui-button-push.wav
  Projects/Ball Ninja Game/style.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#468 Blog Website
  Projects/Blog Project Website/README.md
  Projects/Blog Project Website/blogpost.html
  Projects/Blog Project Website/contact.html
  Projects/Blog Project Website/css/blogpost.css
  Projects/Blog Project Website/css/contact.css
  Projects/Blog Project Website/css/mobile.css
  Projects/Blog Project Website/css/style.css
  Projects/Blog Project Website/css/utils.css
  Projects/Blog Project Website/img/1.png
  Projects/Blog Project Website/img/11.svg
  Projects/Blog Project Website/img/2.png
  Projects/Blog Project Website/img/3.png
  Projects/Blog Project Website/img/Vecteezy_Diwali-Illustration_ba1020.jpg
  Projects/Blog Project Website/img/home.svg
  Projects/Blog Project Website/img/logo.png
  Projects/Blog Project Website/index.html
  Projects/Blog Project Website/search.html
Labels: Medium, SWOC 3.0

#497 Jumble Word Project
  Projects/JumbleWord/index.html
  Projects/JumbleWord/readme.md
  Projects/JumbleWord/script.js
  Projects/JumbleWord/style.css
  Projects/JumbleWord/words.js
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#498 Countify
  Projects/countify/index.html
  Projects/countify/readme.md
  Projects/countify/script.js
  Projects/countify/style.css
Labels: Beginner, SWOC 3.0

#508 Resolved #201
  Projects/BMICalculator/scripts.js
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#513 Filters
  Projects/Filters/README.md
  Projects/Filters/app.js
  Projects/Filters/index.html
  Projects/Filters/products.js
  Projects/Filters/styles.css
Labels: Approved, Beginner, Ready to merge, SWOC 3.0

#517 Dont hit on road game using js
  Projects/Dont hit on Road/README.md
  Projects/Dont hit on Road/dist/index.html
  Projects/Dont hit on Road/dist/script.js
  Projects/Dont hit on Road/dist/style.css
  Projects/Dont hit on Road/src/index.html
  Projects/Dont hit on Road/src/script.js
  Projects/Dont hit on Road/src/style.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#522 added music player
  Projects/musicPlayer/README.md
  Projects/musicPlayer/index.html
  Projects/musicPlayer/main.js
  Projects/musicPlayer/style.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0

#454 Initial commit for snake,water & Gun game
  Projects/The Snake,Water and Gun Game/Readme.md
  Projects/The Snake,Water and Gun Game/images/img1.png
  Projects/The Snake,Water and Gun Game/images/output.PNG
  Projects/The Snake,Water and Gun Game/index.html
  Projects/The Snake,Water and Gun Game/script.js
  Projects/The Snake,Water and Gun Game/style.css
Labels: Approved, Medium, Ready to merge, SWOC 3.0
