Repository TusharKesarwani/Front-End-Projects, pull requests merged in 2023-06, with the labels that each got.

#888 Fixed the Issue #783 Multiple Operators in Calculator.
  Projects/Calculator/js/script.js
Labels: Approved, Ready to merge

#934 #928 - Added question navigation panel and updated README in "Dynamic Quiz Js"
  Projects/Dynamic js Quiz/README.md
  Projects/Dynamic js Quiz/index.html
  Projects/Dynamic js Quiz/style.css
  Projects/Dynamic js Quiz/text.js
Labels: Approved, Ready to merge

#1008 Fixed image not displaying issue in "BMI Calculator" project
  Projects/BMICalculator/scripts.js
  Projects/BMICalculator/style.css
Labels: Approved, Ready to merge

#864 Feat: Realtime Currency Converter Project using API.
  Projects/Realtime Currency Converter/README.md
  Projects/Realtime Currency Converter/coinExchangeSticker.png
  Projects/Realtime Currency Converter/currencyCodes.js
  Projects/Realtime Currency Converter/index.html
  Projects/Realtime Currency Converter/script.js
  Projects/Realtime Currency Converter/style.css
  img/projects/CurrencyConverter.png
  projects.js
Labels: Approved, Ready to merge

#1090 ADD : Resume Creator
  Projects/Resume Creator/README.md
  Projects/Resume Creator/Screenshot_20221224_150710.png
  Projects/Resume Creator/Screenshot_20221224_150727.png
  Projects/Resume Creator/app.js
  Projects/Resume Creator/index.html
  Projects/Resume Creator/style.css
  img/projects/Resume_Creator.png
  projects.js
Labels: Approved, Ready to merge, SSOC 2.0

#1158 Fixed UI and updated theme in Bookcase project
  Projects/Bookcase/assets/bgImage.png
  Projects/Bookcase/assets/check-outline.svg
  Projects/Bookcase/assets/check-solid.svg
  Projects/Bookcase/assets/trash-fill.svg
  Projects/Bookcase/assets/trash-outline.svg
  Projects/Bookcase/assets/undo-ouline.svg
  Projects/Bookcase/css/style.css
  Projects/Bookcase/index.html
  Projects/Bookcase/js/data.js
  Projects/Bookcase/js/dom.js
  Projects/Bookcase/js/script.js
  Projects/Bookcase/script.js
Labels: Approved, Ready to merge

#1189 Added Word Counter Website
  Projects/Word Counter/index.html
  Projects/Word Counter/script.js
  Projects/Word Counter/style.css
Labels: Ready to merge, SSOC 2.0

#1195 Fevicon Fetcher UI updated [SSOC 2.O]
  Projects/Favicon Fetcher/README.md
  Projects/Favicon Fetcher/images/background.avif
  Projects/Favicon Fetcher/index.html
  Projects/Favicon Fetcher/styles.css
Labels: Ready to merge, SSOC 2.0

#1275 facebook front page clone
  Projects/Facebook Clone/images/add-account.png
  Projects/Facebook Clone/images/facebook-icon.svg
  Projects/Facebook Clone/images/facebook.png
  Projects/Facebook Clone/images/user.jpg
  Projects/Facebook Clone/index.html
  Projects/Facebook Clone/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1273 Logistic Company Landing Page added
  Projects/Logistic Company/img/img 5 (1).jpg
  Projects/Logistic Company/img/img1 (1).jpg
  Projects/Logistic Company/img/img3 (1).jpg
  Projects/Logistic Company/img/img3.webp
  Projects/Logistic Company/img/plane.jpg
  Projects/Logistic Company/img/ship.jpeg
  Projects/Logistic Company/img/ship.png
  Projects/Logistic Company/img/truck.jpeg
  Projects/Logistic Company/index.html
  Projects/Logistic Company/style.css
  img/projects/logiC.png
  projects.js
Labels: Approved, Ready to merge, SSOC 2.0

#1270 Tourism
  Projects/Tourism/README.md
  Projects/Tourism/index.html
  Projects/Tourism/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1255 Cafe-Landing-Page
  Projects/CafeLandingPage/images/cake1.PNG
  Projects/CafeLandingPage/images/cake2.PNG
  Projects/CafeLandingPage/images/deck1.PNG
  Projects/CafeLandingPage/images/deck2.PNG
  Projects/CafeLandingPage/images/deck3.PNG
  Projects/CafeLandingPage/images/deck4.PNG
  Projects/CafeLandingPage/images/final1.PNG
  Projects/CafeLandingPage/images/final2.PNG
  Projects/CafeLandingPage/images/final3.PNG
  Projects/CafeLandingPage/images/final4.PNG
  Projects/CafeLandingPage/images/final5.PNG
  Projects/CafeLandingPage/images/final6.PNG
  Projects/CafeLandingPage/images/first.PNG
  Projects/CafeLandingPage/images/logo.PNG
  Projects/CafeLandingPage/images/logo1.PNG
  Projects/CafeLandingPage/images/maining.jfif
  Projects/CafeLandingPage/images/one.jfif
  Projects/CafeLandingPage/images/soon.PNG
  Projects/CafeLandingPage/images/yoo.PNG
  Projects/CafeLandingPage/index.html
  Projects/CafeLandingPage/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1241 Armstrong checker UI changes done
  Projects/ArmstrongChecker/OpenSans-Semibold.ttf
  Projects/ArmstrongChecker/armstrong.css
Labels: Approved, Ready to merge, SSOC 2.0

#1073 Add Book Buddy project
  Projects/Book Buddy/README.md
  Projects/Book Buddy/back.jpg
  Projects/Book Buddy/index.html
  Projects/Book Buddy/script.js
  Projects/Book Buddy/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1261 Slidding Box Loader
  Projects/sliding box loader/index.html
  Projects/sliding box loader/script.js
  Projects/sliding box loader/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1252 added cafe website - A website which provides details of the nearest cafes to people
  Projects/Cafe Website/css/styles.css
  Projects/Cafe Website/images/favicon.svg
  Projects/Cafe Website/images/iphone6.png
  Projects/Cafe Website/index.html
Labels: Approved, Ready to merge, SSOC 2.0

#967 Updated index.html (solving issue #966)
  Projects/Student Service Portal/index.html
Labels: Approved, SSOC 2.0

#1244 enhanced the ping-pong game UI and also added sounds in game
  Projects/Ping-Png/700.css
  Projects/Ping-Png/Paddle.js
  Projects/Ping-Png/app.js
  Projects/Ping-Png/ball.js
  Projects/Ping-Png/index.html
  Projects/Ping-Png/sounds/ballHitBat.wav
  Projects/Ping-Png/sounds/gainpoint.mp3
  Projects/Ping-Png/sounds/losspoint.mp3
  Projects/Ping-Png/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1000 changing temperature into kelvin and rankine.
  Projects/Temperatureconverter/index.html
Labels: Approved, Ready to merge, SSOC 2.0

#1028 [Solved issue: #817] : Fixed the issue of checking palindrome.
  Projects/palindrome/palindrome.css
  Projects/palindrome/palindrome.html
  Projects/palindrome/palindrome.js
Labels: Approved, Ready to merge, SSOC 2.0

#1072 added hover to contributors section
  style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1357 added scrollbar button
  index.html
  script.js
  style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1186 issue #837 fetching memes Reddit
  Projects/Fetch-Reddit-Memes/README.md
  Projects/Fetch-Reddit-Memes/image.png
  Projects/Fetch-Reddit-Memes/meme.jpg
  Projects/Fetch-Reddit-Memes/redditmemes.css
  Projects/Fetch-Reddit-Memes/redditmemes.html
  Projects/Fetch-Reddit-Memes/redditmemes.js
Labels: Approved, Ready to merge, SSOC 2.0

#1214 Feature/adding download option
  Projects/QR Code Generator/Index.html
  Projects/QR Code Generator/script.js
  Projects/QR Code Generator/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1402 Made the text visible
  Projects/Tripocity/index.html
Labels: Approved, Ready to merge

#1397 Palindrome UI --changes
  Projects/palindrome/palindrome.css
  Projects/palindrome/palindrome.html
  Projects/palindrome/palindrome.js
Labels: Approved, Ready to merge, SSOC 2.0

#1385 Updated the range in BMI Calculator
  Projects/BMICalculator/README.md
  Projects/BMICalculator/index.html
  Projects/BMICalculator/scripts.js
  Projects/BMICalculator/style.css
Labels: Approved, Ready to merge

#1362 [SSoC 2.0] Morse Code Convertor Project Completed
  Projects/Morse Code Convertor/README.md
  Projects/Morse Code Convertor/images/bg.jpg
  Projects/Morse Code Convertor/images/favicon.ico
  Projects/Morse Code Convertor/index.html
  Projects/Morse Code Convertor/script.js
  Projects/Morse Code Convertor/style.css
  img/projects/Morse_Code_Convertor.png
  projects.js
Labels: Approved, Ready to merge, SSOC 2.0

#1346 Added Auto text effect animation
  Projects/Auto Text Effect Animation/README.MD
  Projects/Auto Text Effect Animation/index.html
  Projects/Auto Text Effect Animation/index.js
  Projects/Auto Text Effect Animation/style.css
  img/projects/Auto Text Effect Animation.png
Labels: Approved, Ready to merge, SSOC 2.0

#1345 added _twitter_clone
  Projects/Twitter_clone/Readme.md
  Projects/Twitter_clone/Twitter-logo.svg
  Projects/Twitter_clone/favicon/android-chrome-192x192.png
  Projects/Twitter_clone/favicon/android-chrome-512x512.png
  Projects/Twitter_clone/favicon/apple-touch-icon.png
  Projects/Twitter_clone/favicon/favicon-16x16.png
  Projects/Twitter_clone/favicon/favicon-32x32.png
  Projects/Twitter_clone/favicon/favicon.ico
  Projects/Twitter_clone/favicon/site.webmanifest
  Projects/Twitter_clone/index.html
  Projects/Twitter_clone/style1.css
Labels: Approved, Ready to merge, SSOC 2.0

#1333 Updated the Button
  Projects/Animated Card/animated_card.css
Labels: Approved, Ready to merge, SSOC 2.0

#1327 Weather
  Projects/Weather/about.html
  Projects/Weather/guide.html
  Projects/Weather/index.html
Labels: Approved, Ready to merge, SSOC 2.0

#1316 Changing Project Card Style
  style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1188 Advice generator app by Shefali
  Projects/Advice Generator/images/bg.jpg
  Projects/Advice Generator/index.html
  Projects/Advice Generator/index.js
  Projects/Advice Generator/styles.css
Labels: Approved, Ready to merge, SSOC 2.0

#1088 Social Media Reference Landing Page project added [SSOC 2.0]
  Projects/Social Media Reference Landing Page/README.md
  Projects/Social Media Reference Landing Page/background_img.jpg
  Projects/Social Media Reference Landing Page/favicon.png
  Projects/Social Media Reference Landing Page/index.html
  Projects/Social Media Reference Landing Page/profile.png
  Projects/Social Media Reference Landing Page/sytle.css
  Projects/Social Media Reference Landing Page/tick.svg
Labels: Approved, Ready to merge, SSOC 2.0

#1036 Tip calculator
  Projects/Tip Calculator/README.MD
  Projects/Tip Calculator/index.html
  Projects/Tip Calculator/script.js
  Projects/Tip Calculator/styles.css
Labels: Approved, Ready to merge, SSOC 2.0

#1443 Beauty zone
  Projects/beautyzone/css/style.min.css
  Projects/beautyzone/index.html
Labels: Approved, Ready to merge, SSOC 2.0

#1442 [SSoC 2.0] Leap Years In Range Project Ready
  Projects/Leap_Years_In_A_Range/README.md
  Projects/Leap_Years_In_A_Range/favicon.ico
  Projects/Leap_Years_In_A_Range/index.html
  Projects/Leap_Years_In_A_Range/script.js
  Projects/Leap_Years_In_A_Range/style.css
  img/projects/Leap_Years_In_A_Range.png
  projects.js
Labels: Approved, Ready to merge, SSOC 2.0

#1441 [SSoC 2.0] Guess Gender By Name Project Completed
  Projects/Guess The Gender By Name/README.md
  Projects/Guess The Gender By Name/female.svg
  Projects/Guess The Gender By Name/index.html
  Projects/Guess The Gender By Name/logo.svg
  Projects/Guess The Gender By Name/male.svg
  Projects/Guess The Gender By Name/script.js
  Projects/Guess The Gender By Name/style.css
  img/projects/Guess_The_Gender.png
  projects.js
Labels: Approved, Ready to merge, SSOC 2.0

#1428 Added ReadMe file to the Dictionary web_app
  Projects/Dictionary_WebApp/README.md
Labels: Approved, Ready to merge, SSOC 2.0

#1471 Blog project
  Projects/Blog Project Website/contact.html
  Projects/Blog Project Website/css/contact.css
Labels: Approved, Ready to merge, SSOC 2.0

#1469 Added ReadMe file to the Drink Water Reminder project
  Projects/DrinkWaterReminderApplication/README.md
Labels: Approved, Ready to merge, SSOC 2.0

#1129 Added Youtube Clone under SSOC '23
  Projects/Youtube-clone/Channel Pictures/t1.webp
  Projects/Youtube-clone/Channel Pictures/t10.jpeg
  Projects/Youtube-clone/Channel Pictures/t11.webp
  Projects/Youtube-clone/Channel Pictures/t12.jpeg
  Projects/Youtube-clone/Channel Pictures/t2.webp
  Projects/Youtube-clone/Channel Pictures/t3.jpeg
  Projects/Youtube-clone/Channel Pictures/t4.jpeg
  Projects/Youtube-clone/Channel Pictures/t5.webp
  Projects/Youtube-clone/Channel Pictures/t6.jpeg
  Projects/Youtube-clone/Channel Pictures/t7.webp
  Projects/Youtube-clone/Channel Pictures/t8.jpeg
  Projects/Youtube-clone/Channel Pictures/t9.webp
  Projects/Youtube-clone/README.md
  Projects/Youtube-clone/Thumbnails/1.webp
  Projects/Youtube-clone/Thumbnails/10.jpeg
  Projects/Youtube-clone/Thumbnails/11.webp
  Projects/Youtube-clone/Thumbnails/12.jpeg
  Projects/Youtube-clone/Thumbnails/2.jpeg
  Projects/Youtube-clone/Thumbnails/3.webp
  Projects/Youtube-clone/Thumbnails/4.jpeg
  Projects/Youtube-clone/Thumbnails/5.webp
  Projects/Youtube-clone/Thumbnails/6.jpeg
  Projects/Youtube-clone/Thumbnails/7.webp
  Projects/Youtube-clone/Thumbnails/8.jpeg
  Projects/Youtube-clone/Thumbnails/9.webp
  Projects/Youtube-clone/Youtube.html
  Projects/Youtube-clone/icons/explore.svg
  Projects/Youtube-clone/icons/hamburger-menu.svg
  Projects/Youtube-clone/icons/home.svg
  Projects/Youtube-clone/icons/library.svg
  Projects/Youtube-clone/icons/my-channel.jpg
  Projects/Youtube-clone/icons/notifications.svg
  Projects/Youtube-clone/icons/originals.svg
  Projects/Youtube-clone/icons/search.svg
  Projects/Youtube-clone/icons/subscriptions.svg
  Projects/Youtube-clone/icons/upload.svg
  Projects/Youtube-clone/icons/voice-search-icon.svg
  Projects/Youtube-clone/icons/youtube-apps.svg
  Projects/Youtube-clone/icons/youtube-logo.svg
  Projects/Youtube-clone/icons/youtube-music.svg
  Projects/Youtube-clone/styles/general.css
  Projects/Youtube-clone/styles/header.css
  Projects/Youtube-clone/styles/sidebar.css
  Projects/Youtube-clone/styles/video.css
Labels: Approved, Ready to merge, SSOC 2.0

#1206 #849 Fixed Overwriting of another Player in "TIC-TAC-TOE PROJECT”
  .DS_Store
  Projects/TIC-TAC-TOE PROJECT/index.js
Labels: Approved, Ready to merge, SSOC 2.0

#1215 Updated Google Drive Clone
  Projects/Google Drive Clone/Google-Drive-Clone-main/images/Google_Drive_23645.ico
  Projects/Google Drive Clone/Google-Drive-Clone-main/index.html
  Projects/Google Drive Clone/Google-Drive-Clone-main/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1302 Adding footer and login/ SignUp page in "Villa Hotel"
  Projects/Villa Hotel website/Login.html
  Projects/Villa Hotel website/about.html
  Projects/Villa Hotel website/blog.html
  Projects/Villa Hotel website/contact.html
  Projects/Villa Hotel website/images/Loginbg.jpg
  Projects/Villa Hotel website/images/bg1.png
  Projects/Villa Hotel website/images/bg2.png
  Projects/Villa Hotel website/images/bg3.png
  Projects/Villa Hotel website/index.html
  Projects/Villa Hotel website/login.js
  Projects/Villa Hotel website/style.css
  Projects/Villa Hotel website/style_a.css
  Projects/Villa Hotel website/style_b.css
  Projects/Villa Hotel website/style_c.css
  Projects/Villa Hotel website/style_l.css
Labels: Approved, Ready to merge, SSOC 2.0

#1539 Added Text-Utilities
  Projects/Text-Utilities/index.html
  Projects/Text-Utilities/script.js
  img/projects/Text_Utils.png
  projects.js
Labels: Approved, Ready to merge, SSOC 2.0
