Repository TusharKesarwani/Front-End-Projects, pull requests merged in 2023-03, with the labels that each got.

#650 Lyrics Search Website
  Projects/Lyrics Search/README.md
  Projects/Lyrics Search/index.html
  Projects/Lyrics Search/script.js
  Projects/Lyrics Search/style.css
Labels: Beginner, SWOC 3.0

#658 Caesar Cipher
  Projects/caesar cipher/Readme.md
  Projects/caesar cipher/index.html
  Projects/caesar cipher/script.js
  Projects/caesar cipher/styles.css
Labels: Medium, Ready to merge, SWOC 3.0

#690 Google clone
  Projects/Google Clone/Readme.md
  Projects/Google Clone/icon.jpg
  Projects/Google Clone/img1.jpg
  Projects/Google Clone/index.html
  Projects/Google Clone/style.css
Labels: Medium, Ready to merge, SWOC 3.0

#699 Pdf Merger App , Instagram Reels Clone App
  Projects/Instagram reels clone/.firebaserc
  Projects/Instagram reels clone/.gitignore
  Projects/Instagram reels clone/README.md
  Projects/Instagram reels clone/firebase-debug.log
  Projects/Instagram reels clone/firebase.json
  Projects/Instagram reels clone/package-lock.json
  Projects/Instagram reels clone/package.json
  Projects/Instagram reels clone/public/favicon.ico
  Projects/Instagram reels clone/public/index.html
  Projects/Instagram reels clone/public/logo192.png
  Projects/Instagram reels clone/public/logo512.png
  Projects/Instagram reels clone/public/manifest.json
  Projects/Instagram reels clone/public/robots.txt
  Projects/Instagram reels clone/src/App.css
  Projects/Instagram reels clone/src/App.js
  Projects/Instagram reels clone/src/VideoCard.css
  Projects/Instagram reels clone/src/VideoCard.js
  Projects/Instagram reels clone/src/VideoFooter.css
  Projects/Instagram reels clone/src/VideoFooter.js
  Projects/Instagram reels clone/src/VideoHeader.css
  Projects/Instagram reels clone/src/VideoHeader.js
  Projects/Instagram reels clone/src/firebase.js
  Projects/Instagram reels clone/src/index.css
  Projects/Instagram reels clone/src/index.js
  Projects/Instagram reels clone/src/serviceWorker.js
  Projects/PdfMerger/README.md
  Projects/PdfMerger/index.html
  Projects/PdfMerger/merge.js
  Projects/PdfMerger/package-lock.json
  Projects/PdfMerger/package.json
  Projects/PdfMerger/server.js
  Projects/PdfMerger/server1.js
  Projects/PdfMerger/uploadfile.js
Labels: Medium, SWOC 3.0

#703 TinyMCE Synonyms Plugin
  Projects/My Calculator_SrishtiJaiswal/index.html
  Projects/My Calculator_SrishtiJaiswal/main.js
  Projects/My Calculator_SrishtiJaiswal/style.css
  Projects/My Calculator_SrishtiJaiswal/utils.css
  Projects/TinyMCE synonym plugin/index.html
  Projects/TinyMCE synonym plugin/script.js
  Projects/TinyMCE synonym plugin/style.css
Labels: Medium, SWOC 3.0

#708 World Info Website
  Projects/World Info Website/README.md
  Projects/World Info Website/index.html
  Projects/World Info Website/script.js
  Projects/World Info Website/style.css
Labels: Medium, SWOC 3.0

#711 Myntra Clone Uploaded
  Projects/myntra-clone/README.md
  Projects/myntra-clone/home.png
  Projects/myntra-clone/index.html
  Projects/myntra-clone/logo.png
  Projects/myntra-clone/script.js
  Projects/myntra-clone/style.css
  Projects/myntra-clone/utils.css
Labels: Medium, SWOC 3.0
