Repository TusharKesarwani/Front-End-Projects, pull requests merged in 2023-07, with the labels that each got.

#1528 Dictionary
  Projects/dictionary/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1521 changed white-space:pre to white-space:normal
  Projects/beautyzone/css/style.min.css
Labels: Approved, Ready to merge, SSOC 2.0

#1169 Added Age calculator
  Projects/Age Calculator/README.md
  Projects/Age Calculator/index.html
  Projects/Age Calculator/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1360 DSA solver webpages(solve issue #922)
  Projects/DsaSolver/README.md
  Projects/DsaSolver/assests/Problem_tabel/Array/Array.html
  Projects/DsaSolver/assests/Problem_tabel/Bitsmanupulation/bits.html
  Projects/DsaSolver/assests/Problem_tabel/Dynamic_programing/dynamic.html
  Projects/DsaSolver/assests/Problem_tabel/Graph/graph.html
  Projects/DsaSolver/assests/Problem_tabel/Linked list/linked_list.html
  Projects/DsaSolver/assests/Problem_tabel/Maths/maths.html
  Projects/DsaSolver/assests/Problem_tabel/Recursion/recursion.html
  Projects/DsaSolver/assests/Problem_tabel/Searching/Searching.html
  Projects/DsaSolver/assests/Problem_tabel/Sorting/Sorting.html
  Projects/DsaSolver/assests/Problem_tabel/Stack_Queue/stack_queue.html
  Projects/DsaSolver/assests/Problem_tabel/String/string.html
  Projects/DsaSolver/assests/Problem_tabel/tree/tree.html
  Projects/DsaSolver/assests/image/Array.png
  Projects/DsaSolver/assests/image/DynamicPrograming.png
  Projects/DsaSolver/assests/image/Graph.png
  Projects/DsaSolver/assests/image/LinkedList.png
  Projects/DsaSolver/assests/image/Mylog.png
  Projects/DsaSolver/assests/image/Queue.png
  Projects/DsaSolver/assests/image/String.png
  Projects/DsaSolver/assests/image/Trees.png
  Projects/DsaSolver/assests/image/bits.png
  Projects/DsaSolver/assests/image/mathematics-circular-flat-vector-20232263.jpg
  Projects/DsaSolver/assests/image/maxresdefault.jpg
  Projects/DsaSolver/assests/image/seraching.jfif
  Projects/DsaSolver/assests/image/sorting.jpg
  Projects/DsaSolver/assests/readme_img/Screenshot 2023-06-20 001525.png
  Projects/DsaSolver/assests/readme_img/Screenshot 2023-06-20 001614.png
  Projects/DsaSolver/assests/readme_img/Screenshot 2023-06-20 001637.png
  Projects/DsaSolver/assests/readme_img/Screenshot 2023-06-20 001654.png
  Projects/DsaSolver/index.html
  Projects/DsaSolver/script.js
  Projects/DsaSolver/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1414 Added Random Emoji Generator
  Projects/Random Emoji Generator/README.md
  Projects/Random Emoji Generator/app.js
  Projects/Random Emoji Generator/image.png
  Projects/Random Emoji Generator/index.html
  Projects/Random Emoji Generator/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1427 Added ReadMe file to the Cafe Website
  Projects/Cafe Website/README.md
Labels: Approved, Ready to merge, SSOC 2.0

#1429 Timer ReadMe added
  Projects/Timer/image.png
  Projects/Timer/readme.md
Labels: Approved, Ready to merge

#1438 QR Code Reader
  Projects/QR Code Reader/.gitignore
  Projects/QR Code Reader/README.md
  Projects/QR Code Reader/assets/favicon.ico
  Projects/QR Code Reader/index.html
  Projects/QR Code Reader/package-lock.json
  Projects/QR Code Reader/package.json
  Projects/QR Code Reader/src/script.js
  Projects/QR Code Reader/styles/styles.css
  Projects/QR Code Reader/tempCodeRunnerFile.js
  img/projects/QR Code Reader.png
  projects.js
Labels: Approved, Ready to merge, SSOC 2.0

#1447 added unit convertor Closes #1389
  Projects/Unit Convertor/index.css
  Projects/Unit Convertor/index.html
  Projects/Unit Convertor/index.js
Labels: Approved, Ready to merge, SSOC 2.0

#1465 Add Frequently Asked Questions component
  Projects/SSOC Frequently Asked Questions/README.md
  Projects/SSOC Frequently Asked Questions/index.html
  Projects/SSOC Frequently Asked Questions/index.js
  Projects/SSOC Frequently Asked Questions/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1500 (Project) issue #1378 coinbase landing page clone
  Projects/Coinbase-clone-clean/README.md
  Projects/Coinbase-clone-clean/assets/css/index.css
  Projects/Coinbase-clone-clean/assets/img/COIN-a63dbab3.png
  Projects/Coinbase-clone-clean/assets/img/Consumer_Wordmark.svg
  Projects/Coinbase-clone-clean/assets/img/amp.png
  Projects/Coinbase-clone-clean/assets/img/bg.png
  Projects/Coinbase-clone-clean/assets/img/bitcoin.png
  Projects/Coinbase-clone-clean/assets/img/calendar.svg
  Projects/Coinbase-clone-clean/assets/img/cardano.png
  Projects/Coinbase-clone-clean/assets/img/chart btc.png
  Projects/Coinbase-clone-clean/assets/img/chart.svg
  Projects/Coinbase-clone-clean/assets/img/coin-charts/adaChart.svg
  Projects/Coinbase-clone-clean/assets/img/coin-charts/btcChart.svg
  Projects/Coinbase-clone-clean/assets/img/coin-charts/ethChart.svg
  Projects/Coinbase-clone-clean/assets/img/coin-charts/solChart.svg
  Projects/Coinbase-clone-clean/assets/img/ethereum.png
  Projects/Coinbase-clone-clean/assets/img/features.jpg
  Projects/Coinbase-clone-clean/assets/img/freeMoney-1.5.webp
  Projects/Coinbase-clone-clean/assets/img/grt.png
  Projects/Coinbase-clone-clean/assets/img/image_26.webp
  Projects/Coinbase-clone-clean/assets/img/instructions-svgs/account.svg
  Projects/Coinbase-clone-clean/assets/img/instructions-svgs/bank.svg
  Projects/Coinbase-clone-clean/assets/img/instructions-svgs/buy.svg
  Projects/Coinbase-clone-clean/assets/img/near.png
  Projects/Coinbase-clone-clean/assets/img/phone.svg
  Projects/Coinbase-clone-clean/assets/img/shping.png
  Projects/Coinbase-clone-clean/assets/img/solana.png
  Projects/Coinbase-clone-clean/assets/img/vault.svg
  Projects/Coinbase-clone-clean/image.png
  Projects/Coinbase-clone-clean/index.html
Labels: Approved, Ready to merge, SSOC 2.0

#1514 Bookmark application
  Projects/Bookmarker_App/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1518 Update script.js
  Projects/WhiteBoard/script.js
Labels: Approved, Ready to merge, SSOC 2.0

#1533 Mobile Shoping Website
  Projects/mobile-shopee/README.md
  Projects/mobile-shopee/assets/Banner1.png
  Projects/mobile-shopee/assets/Banner2.png
  Projects/mobile-shopee/assets/banner1-cr-500x150.jpg
  Projects/mobile-shopee/assets/banner2-cr-500x150.jpg
  Projects/mobile-shopee/assets/blog/blog1.jpg
  Projects/mobile-shopee/assets/blog/blog2.jpg
  Projects/mobile-shopee/assets/blog/blog3.jpg
  Projects/mobile-shopee/assets/blog/empty_cart.png
  Projects/mobile-shopee/assets/products/1.png
  Projects/mobile-shopee/assets/products/10.png
  Projects/mobile-shopee/assets/products/11.png
  Projects/mobile-shopee/assets/products/12.png
  Projects/mobile-shopee/assets/products/13.png
  Projects/mobile-shopee/assets/products/14.png
  Projects/mobile-shopee/assets/products/15.png
  Projects/mobile-shopee/assets/products/2.png
  Projects/mobile-shopee/assets/products/3.png
  Projects/mobile-shopee/assets/products/4.png
  Projects/mobile-shopee/assets/products/5.png
  Projects/mobile-shopee/assets/products/6.png
  Projects/mobile-shopee/assets/products/8.png
  Projects/mobile-shopee/cart.html
  Projects/mobile-shopee/index.html
  Projects/mobile-shopee/index.js
  Projects/mobile-shopee/main.css
  Projects/mobile-shopee/main.css.map
  Projects/mobile-shopee/package-lock.json
  Projects/mobile-shopee/package.json
  Projects/mobile-shopee/product.html
  Projects/mobile-shopee/sass/includ/color.scss
  Projects/mobile-shopee/sass/includ/global.scss
  Projects/mobile-shopee/sass/includ/special-price.scss
  Projects/mobile-shopee/sass/includ/top-sale.scss
  Projects/mobile-shopee/sass/includ/typograph.scss
  Projects/mobile-shopee/sass/includ/variable.scss
  Projects/mobile-shopee/sass/main.scss
  img/projects/mobile-shopee.png
Labels: Approved, Ready to merge, SSOC 2.0

#1507 [SSoC 2.0] Playable Piano Project Completed
  Projects/Playable_Piano/README.md
  Projects/Playable_Piano/favicon.ico
  Projects/Playable_Piano/index.html
  Projects/Playable_Piano/script.js
  Projects/Playable_Piano/style.css
  Projects/Playable_Piano/tunes/;.wav
  Projects/Playable_Piano/tunes/a.wav
  Projects/Playable_Piano/tunes/d.wav
  Projects/Playable_Piano/tunes/e.wav
  Projects/Playable_Piano/tunes/f.wav
  Projects/Playable_Piano/tunes/g.wav
  Projects/Playable_Piano/tunes/h.wav
  Projects/Playable_Piano/tunes/j.wav
  Projects/Playable_Piano/tunes/k.wav
  Projects/Playable_Piano/tunes/l.wav
  Projects/Playable_Piano/tunes/o.wav
  Projects/Playable_Piano/tunes/p.wav
  Projects/Playable_Piano/tunes/s.wav
  Projects/Playable_Piano/tunes/t.wav
  Projects/Playable_Piano/tunes/u.wav
  Projects/Playable_Piano/tunes/w.wav
  Projects/Playable_Piano/tunes/y.wav
  img/projects/Playable_Piano.png
  projects.js
Labels: Approved, Ready to merge, SSOC 2.0

#1415 [SSoC 2.0] Sound Equalizer Project Complete
  Projects/Sound_Equalizer/README.md
  Projects/Sound_Equalizer/favicon.ico
  Projects/Sound_Equalizer/index.html
  Projects/Sound_Equalizer/script.js
  Projects/Sound_Equalizer/style.css
  img/projects/Sound_Equalizer.png
  projects.js
Labels: Approved, Ready to merge, SSOC 2.0

#1555 Ecommerce landing page
  Projects/E-commerce Landing Page/styles.css
Labels: Approved, Ready to merge, SSOC 2.0

#1570 Made Mixtape site Responsive
  Projects/Mixtape/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1574 favicon site responsive now
  Projects/Favicon Fetcher/index.html
  Projects/Favicon Fetcher/styles.css
Labels: Approved, Ready to merge, SSOC 2.0

#1588 Text overflow solved (Image Editor)
  Projects/image editor/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1589 content overflow solved and CSS improved (Pincode Checker)
  Projects/Pincode checker/index.html
  Projects/Pincode checker/styles.css
Labels: Approved, Ready to merge, SSOC 2.0

#1413 [SSoC 2.0] Solar System Model Ready
  Projects/Solar System Model/README.md
  Projects/Solar System Model/favicon.ico
  Projects/Solar System Model/index.html
  Projects/Solar System Model/script.js
  Projects/Solar System Model/style.css
  img/projects/Solar_System_Model.png
  projects.js
Labels: enhancement, SSOC 2.0

#1105 Added the Bakery Website
  Projects/Bakery_Website/Lava-Cake-PNG-Free-Download.png
  Projects/Bakery_Website/Pastry-PNG-Images.png
  Projects/Bakery_Website/cake.png
  Projects/Bakery_Website/cookie-cliparts-transparent-download-clip-art-17.png
  Projects/Bakery_Website/crossiant.png
  Projects/Bakery_Website/garlic-bread.png
  Projects/Bakery_Website/hot-choco.png
  Projects/Bakery_Website/index.html
  Projects/Bakery_Website/lava-cake.png
  Projects/Bakery_Website/logo.png
  Projects/Bakery_Website/mug-of-hot-chocolate-QJGa0QD-600.jpg
  Projects/Bakery_Website/png-transparent-garlic-bread-domino-s-pizza-take-out-italian-cuisine-bread-pasta-baked-goods-food-cheese.png
  Projects/Bakery_Website/style.css
  Projects/Bakery_Website/swiggy.jpg
  Projects/Bakery_Website/wp2443226.jpg
  Projects/Bakery_Website/zomato.png
Labels: Approved, Ready to merge, SSOC 2.0

#1139 Enhanced FAQs
  Projects/Education Website/css/style.css
  Projects/Education Website/main.js
Labels: Approved, Ready to merge, SSOC 2.0

#1140 super burger landiing page
  Projects/Super_Burger_Landing_page/.gitignore
  Projects/Super_Burger_Landing_page/index.html
  Projects/Super_Burger_Landing_page/main.js
  Projects/Super_Burger_Landing_page/package-lock.json
  Projects/Super_Burger_Landing_page/package.json
  Projects/Super_Burger_Landing_page/public/4301493_burger_fast_fastfood_food_hamburger_icon.svg
  Projects/Super_Burger_Landing_page/public/540f74001ca90a19263c66165621d597.gif
  Projects/Super_Burger_Landing_page/public/7429347_food_delivery_service_take away_restaurant_icon.svg
  Projects/Super_Burger_Landing_page/public/BBQ_Dish.png
  Projects/Super_Burger_Landing_page/public/Burger_effect_1.png
  Projects/Super_Burger_Landing_page/public/Burger_month.png
  Projects/Super_Burger_Landing_page/public/Gerald_G_Fast_Food_Lunch_Dinner_(FF_Menu)_6.png
  Projects/Super_Burger_Landing_page/public/fresh_pizza.png
  Projects/Super_Burger_Landing_page/public/ribs.png
  Projects/Super_Burger_Landing_page/public/smoke_burger.png
  Projects/Super_Burger_Landing_page/public/smokey_bacon_1.png
  Projects/Super_Burger_Landing_page/public/steak_1.png
  Projects/Super_Burger_Landing_page/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1157 Netflix landing page clone
  Projects/Netflix-landing-page/img/down-icon.png
  Projects/Netflix-landing-page/img/down.png
  Projects/Netflix-landing-page/img/feature-1.png
  Projects/Netflix-landing-page/img/feature-2.png
  Projects/Netflix-landing-page/img/feature-3.png
  Projects/Netflix-landing-page/img/feature-4.png
  Projects/Netflix-landing-page/img/header-image.png
  Projects/Netflix-landing-page/img/header-img.png
  Projects/Netflix-landing-page/img/logo.png
  Projects/Netflix-landing-page/img/w.png
  Projects/Netflix-landing-page/index.html
  Projects/Netflix-landing-page/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1643 dictionary modified
  Projects/dictionary/index.html
  Projects/dictionary/script.js
  Projects/dictionary/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1636 Ezymath
  Projects/ezymath-main/currencycalculator.html
Labels: Approved, Ready to merge, SSOC 2.0

#1620 number_guessing_game modified
  Projects/number_guessing_game/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1619 World info website modified
  Projects/World Info Website/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1601 prime checker modified
  Projects/prime checker/prime.css
Labels: Approved, Ready to merge, SSOC 2.0

#1598 Bottom scrollbar issue fixed
  Projects/Bookcase/css/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1208 3D Rotating Cube
  Projects/3D Rotating Cube/README.md
  Projects/3D Rotating Cube/index.html
  Projects/3D Rotating Cube/styles.css
Labels: Approved, Ready to merge, SSOC 2.0

#1184 Modifications to the Expense Tracker project.
  Projects/Expense Tracker/index.html
  Projects/Expense Tracker/script.js
  Projects/Expense Tracker/signup.html
  Projects/Expense Tracker/signup_script.js
  Projects/Expense Tracker/style.css
  Projects/Expense Tracker/stylelogin.css
Labels: Approved, Ready to merge, SSOC 2.0

#1641 Countdown Timer Added
  Projects/Countdown Timer/README.md
  Projects/Countdown Timer/bgvideo.mp4
  Projects/Countdown Timer/index.html
  Projects/Countdown Timer/script.js
  Projects/Countdown Timer/style.css
  img/projects/Countdown Timer.png
Labels: Approved, Ready to merge, SSOC 2.0

#1644 Loan calculator modified
  Projects/Loan-calculator/loancalculator.css
  Projects/Loan-calculator/loancalculator.js
Labels: Approved, Ready to merge, SSOC 2.0

#1649 theme switcher modified
  Projects/Theme Switcher/switch_theme_css.css
Labels: Approved, Ready to merge, SSOC 2.0

#1655 Footer Text align and Overflow issue fixed
  Projects/Tripocity/index.html
  Projects/Tripocity/style/style_tripocity1.css
Labels: Approved, Ready to merge, SSOC 2.0

#1663 Weight converter modified
  Projects/Weight_converter/script.js
Labels: Approved, Ready to merge, SSOC 2.0

#1664 tip calulator modified
  Projects/Tip Calculator/script.js
Labels: Approved, Ready to merge, SSOC 2.0

#1678 bill tip calculator modified
  Projects/bill tip calculator/app.js
Labels: Approved, Ready to merge, SSOC 2.0

#1680 temperature converter modified
  Projects/Temperatureconverter/index.html
Labels: Approved, Ready to merge, SSOC 2.0

#1455 Added date function to update date automatically
  Projects/Shades/index.html
Labels: Approved, Ready to merge, SSOC 2.0

#1207 Glowing Text Animations
  Projects/Glowing-Text-Animation/index.html
  Projects/Glowing-Text-Animation/readme.md
  Projects/Glowing-Text-Animation/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1209 3D Navbar Animations
  Projects/3d_Navbar_Animations/app.js
  Projects/3d_Navbar_Animations/bg.jpg
  Projects/3d_Navbar_Animations/index.html
  Projects/3d_Navbar_Animations/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1213 added Graph visualiser
  Projects/graph visuliser/README.md
  Projects/graph visuliser/index.html
  Projects/graph visuliser/script.js
  Projects/graph visuliser/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1230 Add HexToRGBA Project
  Projects/HexToRGBAConverter/index.html
  Projects/HexToRGBAConverter/script.js
Labels: Approved, Ready to merge, SSOC 2.0

#1332 Updated the 3D Login Page
  Projects/3D Login Page/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1394 Enhancement of UI/UX
  Projects/Audio-Text-Converter/index.html
  Projects/Audio-Text-Converter/style.css
  Projects/Audio-Text-Converter/textimage.jpg
Labels: Approved, Ready to merge, SSOC 2.0

#1406 Add logo finder
  Projects/Logo Finder/index.html
  Projects/Logo Finder/logo.png
Labels: Approved, Ready to merge, SSOC 2.0

#1453 closes1370
  Projects/GitHub User Search App/assets/favicon-32x32.png
  Projects/GitHub User Search App/assets/icon-company.svg
  Projects/GitHub User Search App/assets/icon-location.svg
  Projects/GitHub User Search App/assets/icon-moon.svg
  Projects/GitHub User Search App/assets/icon-search.svg
  Projects/GitHub User Search App/assets/icon-sun.svg
  Projects/GitHub User Search App/assets/icon-twitter.svg
  Projects/GitHub User Search App/assets/icon-website.svg
  Projects/GitHub User Search App/index.html
  Projects/GitHub User Search App/screenshot.jpg
  Projects/GitHub User Search App/script.js
  Projects/GitHub User Search App/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1456 adding new social media project name as Socially
  Projects/socialmediaweb/back-image.png
  Projects/socialmediaweb/index.html
  Projects/socialmediaweb/logo.png
  Projects/socialmediaweb/pic.png
  Projects/socialmediaweb/socally/README.md
  Projects/socialmediaweb/socally/back-image.png
  Projects/socialmediaweb/socally/index.html
  Projects/socialmediaweb/socally/logo.png
  Projects/socialmediaweb/socally/pic.png
  Projects/socialmediaweb/socally/style.css
  Projects/socialmediaweb/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1511 Add NFT component
  Projects/NFTCardComponent/README.md
  Projects/NFTCardComponent/images/favicon-32x32.png
  Projects/NFTCardComponent/images/icon-clock.svg
  Projects/NFTCardComponent/images/icon-ethereum.svg
  Projects/NFTCardComponent/images/icon-view.svg
  Projects/NFTCardComponent/images/image-avatar.png
  Projects/NFTCardComponent/images/image-equilibrium.jpg
  Projects/NFTCardComponent/index.html
  Projects/NFTCardComponent/styles.css
Labels: Approved, Ready to merge, SSOC 2.0

#1524 Updated app.js
  Projects/SignIn Page/js/app.js
Labels: Approved, Ready to merge, SSOC 2.0

#1525 Update script.js
  Projects/World Info Website/script.js
Labels: Approved, Ready to merge, SSOC 2.0

#1592 Added my project (t-shirt picker)
  Projects/t-shirt-color-picker-main-master/index.html
  Projects/t-shirt-color-picker-main-master/readme.md
  Projects/t-shirt-color-picker-main-master/t-shirt-294078.svg
Labels: Approved, Ready to merge, SSOC 2.0

#1597 Added ChatBot Project
  Projects/ChatBot/images/chatbot.png
  Projects/ChatBot/images/user.png
  Projects/ChatBot/index.html
  Projects/ChatBot/script.js
  Projects/ChatBot/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1603 Added new project: PokeDex
  Projects/PokeDex/PokeDex.css
  Projects/PokeDex/PokeDex.html
  Projects/PokeDex/PokeDex.js
  Projects/PokeDex/photos/gith.png
  Projects/PokeDex/photos/peakpx.jpg
  Projects/PokeDex/photos/pokemon.png
  Projects/PokeDex/photos/wallpaperflare.com_wallpaper (8).jpg
  Projects/PokeDex/search.js
Labels: Approved, Ready to merge, SSOC 2.0

#1623 Created a png file of icon and added to html
  Projects/Calculator/img/icon.png
  Projects/Calculator/index.html
Labels: Approved, Ready to merge, SSOC 2.0

#1659 add form validations to bmi calculator
  Projects/BMICalculator/scripts.js
Labels: Approved, Ready to merge, SSOC 2.0

#1661 add loading-state to book-buddy, replacing the alert block
  Projects/Book Buddy/script.js
  Projects/Book Buddy/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1677 added beyblade card catalog project with resolving the error in projects.js file
  Projects/Beyblade-Card-Catalog/beyblade.json
  Projects/Beyblade-Card-Catalog/index.css
  Projects/Beyblade-Card-Catalog/index.html
  Projects/Beyblade-Card-Catalog/index.js
  img/projects/Beyblade_Card_Catalog.png
  projects.js
Labels: Approved, Ready to merge, SSOC 2.0

#1699 Adding the budget Manager
  Projects/Budget Manager/app.js
  Projects/Budget Manager/bgimage.png
  Projects/Budget Manager/chart.js
  Projects/Budget Manager/close-circle-outline-expense.svg
  Projects/Budget Manager/close-circle-outline.svg
  Projects/Budget Manager/debug.log
  Projects/Budget Manager/fonts/Gilroy-Bold.woff
  Projects/Budget Manager/fonts/Gilroy-Heavy.woff
  Projects/Budget Manager/fonts/Gilroy-Light.woff
  Projects/Budget Manager/fonts/Gilroy-Medium.woff
  Projects/Budget Manager/fonts/Gilroy-Regular.woff
  Projects/Budget Manager/images/1.jpeg
  Projects/Budget Manager/images/1.png
  Projects/Budget Manager/images/1a.png
  Projects/Budget Manager/images/2a.png
  Projects/Budget Manager/images/3a.png
  Projects/Budget Manager/images/4a.png
  Projects/Budget Manager/images/4b.png
  Projects/Budget Manager/images/5a.png
  Projects/Budget Manager/images/5b.png
  Projects/Budget Manager/images/5c.png
  Projects/Budget Manager/images/5d.png
  Projects/Budget Manager/images/appdemo.gif
  Projects/Budget Manager/images/budget.png
  Projects/Budget Manager/images/budget1.png
  Projects/Budget Manager/images/credit.png
  Projects/Budget Manager/index.html
  Projects/Budget Manager/log_in.html
  Projects/Budget Manager/main.html
  Projects/Budget Manager/outline-expense.svg
  Projects/Budget Manager/outline.svg
  Projects/Budget Manager/output_images/1.png
  Projects/Budget Manager/output_images/2.png
  Projects/Budget Manager/script.js
  Projects/Budget Manager/style.css
  Projects/Budget Manager/styles.css
  Projects/Budget Manager/styles_login.css
  Projects/Budget Manager/trash-outline-expense.svg
  Projects/Budget Manager/trash-outline.svg
Labels: Approved, Ready to merge, SSOC 2.0

#1700 Hover Board Effect Added
  Projects/HoverBoard_Effect/HoverBoardEffect.png
  Projects/HoverBoard_Effect/README.md
  Projects/HoverBoard_Effect/index.html
  Projects/HoverBoard_Effect/script.js
  Projects/HoverBoard_Effect/style.css
  img/projects/HoverBoardEffect.png
Labels: Approved, Ready to merge, SSOC 2.0

#1701 Layout Master Added
  Projects/Layout Master/README.md
  Projects/Layout Master/about.html
  Projects/Layout Master/img.jpg
  Projects/Layout Master/img/data_storage_2_2.png
  Projects/Layout Master/img/desktop_analytics_2.png
  Projects/Layout Master/img/files_2.png
  Projects/Layout Master/img/monitor_coding_2.png
  Projects/Layout Master/img/monitor_settings_2.png
  Projects/Layout Master/img/server_2_2.png
  Projects/Layout Master/img/server_3.png
  Projects/Layout Master/img/server_safe_2.png
  Projects/Layout Master/img/undraw.png
  Projects/Layout Master/index.html
  Projects/Layout Master/style.css
  img/projects/LayoutMaster.png
Labels: Approved, Ready to merge, SSOC 2.0

#1702 Feat/air pollution search place location
  Projects/Air-Quality/countries.js
  Projects/Air-Quality/index.html
  Projects/Air-Quality/script.js
  Projects/Air-Quality/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1705 github profile wrapper modified
  Projects/Github Profile Wrapper/script.js
Labels: Approved, Ready to merge, SSOC 2.0

#1706 feat: add codeql workflow
  .github/workflows/codeql.yml
Labels: Approved, Ready to merge, SSOC 2.0

#1709 Updating-Recipe Finder
  Projects/Recipe Finder/assets/script.js
  Projects/Recipe Finder/assets/scroll.css
  Projects/Recipe Finder/assets/style.css
  Projects/Recipe Finder/index.html
Labels: Approved, Ready to merge, SSOC 2.0

#1719 Basic Banking System Project
  Projects/Basic Banking System/Assets/Gif/Back.gif
  Projects/Basic Banking System/Assets/Gif/Back2.gif
  Projects/Basic Banking System/Assets/img/Back3.jpeg
  Projects/Basic Banking System/Assets/img/Background.png
  Projects/Basic Banking System/Assets/img/Bank.jpg
  Projects/Basic Banking System/Assets/img/bank.png
  Projects/Basic Banking System/Assets/img/logo.png
  Projects/Basic Banking System/Assets/img/navbar.jpg
  Projects/Basic Banking System/README.md
  Projects/Basic Banking System/home.html
  Projects/Basic Banking System/index.css
  Projects/Basic Banking System/index.html
  Projects/Basic Banking System/script.js
  Projects/Basic Banking System/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1722 Made Resume-Builder under SSoC 2023
  Projects/Resume Builder/assets/css/main.css
  Projects/Resume Builder/assets/images/curriculum-vitae.png
  Projects/Resume Builder/assets/images/dublin-resume-templates.avif
  Projects/Resume Builder/assets/images/feature-1-edf4481d69166ac81917d1e40e6597c8d61aa970ad44367ce78049bf830fbda5.svg
  Projects/Resume Builder/assets/images/feature-2-a7a471bd973c02a55d1b3f8aff578cd3c9a4c5ac4fc74423d94ecc04aef3492b.svg
  Projects/Resume Builder/assets/images/feature-3-4e87a82f83e260488c36f8105e26f439fdc3ee5009372bb5e12d9421f32eabdd.svg
  Projects/Resume Builder/assets/images/profile-image.jpg
  Projects/Resume Builder/assets/images/visual-0c7080adf17f1f207276f613447c924f667dab34b7ac415cd7ef653172defd0b.svg
  Projects/Resume Builder/assets/images/visual-13cdbab63916313dab4caff704097bae2aafc990be5e86f9cc50260bffe6bc75.svg
  Projects/Resume Builder/assets/js/app.js
  Projects/Resume Builder/assets/js/script.js
  Projects/Resume Builder/index.html
  Projects/Resume Builder/resume.html
Labels: Approved, Ready to merge, SSOC 2.0

#1550 [SSoC 2.0] Video Player Project Ready
  Projects/Video-Player/README.md
  Projects/Video-Player/index.html
  Projects/Video-Player/logo.png
  Projects/Video-Player/script.js
  Projects/Video-Player/style.css
  Projects/Video-Player/video.mp4
  img/projects/Video_Player.png
  projects.js
Labels: Approved, Ready to merge, SSOC 2.0

#1726 Fixed the Orientation of Clock Face and their Numbers
  Projects/Analog Clock/index.html
  Projects/Analog Clock/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1727 fix: container position over body
  Projects/bill tip calculator/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1735 [SSoC 2.0] Alarm Clock
  Projects/Alarm clock/assets/clock.png
  Projects/Alarm clock/assets/digital_alarm.mp3
  Projects/Alarm clock/index.html
  Projects/Alarm clock/readme.md
  Projects/Alarm clock/script.js
  Projects/Alarm clock/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1740 added Live currency converter Project with responsive design
  Projects/Live Currency Converter/README.md
  Projects/Live Currency Converter/images/image.png
  Projects/Live Currency Converter/images/image2.png
  Projects/Live Currency Converter/images/image3.png
  Projects/Live Currency Converter/index.html
  Projects/Live Currency Converter/index.js
  Projects/Live Currency Converter/styles.css
Labels: Approved, Ready to merge, SSOC 2.0

#1751 Update README.md
  README.md
Labels: Approved, Ready to merge, SSOC 2.0

#1752 Added a feature in Notes App to mark a note as important
  Projects/Notes App/index.html
  Projects/Notes App/script.js
  Projects/Notes App/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1754 Apple landing UI Clone Ready
  Projects/Apple-UI-Clone/img/apple-card-logo.png
  Projects/Apple-UI-Clone/img/apple-card.jpg
  Projects/Apple-UI-Clone/img/apple-card.png
  Projects/Apple-UI-Clone/img/apple-fitness.jpg
  Projects/Apple-UI-Clone/img/apple-logo.png
  Projects/Apple-UI-Clone/img/apple-one-logo.png
  Projects/Apple-UI-Clone/img/apple-one.png
  Projects/Apple-UI-Clone/img/apple-tv-logo.png
  Projects/Apple-UI-Clone/img/apple-watch-6.png
  Projects/Apple-UI-Clone/img/apple-watch-logo.png
  Projects/Apple-UI-Clone/img/dickinson-apple-logo.png
  Projects/Apple-UI-Clone/img/dickinson-apple-tv.jpg
  Projects/Apple-UI-Clone/img/dickinson-apple-tv.png
  Projects/Apple-UI-Clone/img/ipad-air-logo.png
  Projects/Apple-UI-Clone/img/ipad-air.png
  Projects/Apple-UI-Clone/img/iphone12pro-background.jpg
  Projects/Apple-UI-Clone/img/iphone_12.jpg
  Projects/Apple-UI-Clone/img/macbook-air-logo.png
  Projects/Apple-UI-Clone/img/macbook-air.png
  Projects/Apple-UI-Clone/img/macbook-air2.png
  Projects/Apple-UI-Clone/img/watch-series-6.jfif
  Projects/Apple-UI-Clone/index.html
  Projects/Apple-UI-Clone/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1755 Password Checker
  Projects/PasswordChecker/Readme.md
  Projects/PasswordChecker/img.jpeg
  Projects/PasswordChecker/index.html
  Projects/PasswordChecker/index.js
  Projects/PasswordChecker/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1757 CafeLandingPage Readme
  Projects/CafeLandingPage/README.md
Labels: Approved, Ready to merge, SSOC 2.0

#1760 Add new project - MotivationMantra
  Projects/Motivation Mantra/README.md
  Projects/Motivation Mantra/index.html
  Projects/Motivation Mantra/script.js
  Projects/Motivation Mantra/styling.css
Labels: Approved, Ready to merge, SSOC 2.0

#1761 [NEW PROJECT] Packers and Movers Website
  Projects/Movers and Packers Website/README.md
  Projects/Movers and Packers Website/index.html
Labels: Approved, Ready to merge, SSOC 2.0

#1764 Issue No. #1741 [ Fixed New Project Added ] Loopstudios landing page.
  Projects/Loopstudios-landing-page/Index.html
  Projects/Loopstudios-landing-page/script.js
  Projects/Loopstudios-landing-page/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1724 #1144 Added Carbon FootPrint Calculator
  Projects/Carbon-FootPrint-Calc/business.html
  Projects/Carbon-FootPrint-Calc/index.css
  Projects/Carbon-FootPrint-Calc/index.html
  Projects/Carbon-FootPrint-Calc/individual.html
  Projects/Carbon-FootPrint-Calc/script.js
  Projects/Carbon-FootPrint-Calc/style.css
  img/projects/carbonFootCalc.png
  projects.js
Labels: Approved, Ready to merge, SSOC 2.0

#1775 add responsiveness to the meditations app
  Projects/Breathe Meditation/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1520 Code for the issue created.
  Projects/SoulBound_Confession/css/pogo-slider.min.css
  Projects/SoulBound_Confession/css/responsive.css
  Projects/SoulBound_Confession/css/responsiveslides.css
  Projects/SoulBound_Confession/css/style.css
  Projects/SoulBound_Confession/images/apple-touch-icon.png
  Projects/SoulBound_Confession/images/blog-img-01.jpg
  Projects/SoulBound_Confession/images/blog-img-02.jpg
  Projects/SoulBound_Confession/images/blog-img-03.jpg
  Projects/SoulBound_Confession/images/favicon.ico
  Projects/SoulBound_Confession/images/footer-bg.jpg
  Projects/SoulBound_Confession/images/logo.png
  Projects/SoulBound_Confession/images/menu-arrow.png
  Projects/SoulBound_Confession/images/pexels-los-muertos-crew-6836692-1920x1080-24fps.mp4
  Projects/SoulBound_Confession/images/ptn-bg.jpg
  Projects/SoulBound_Confession/images/slider-01.jpg
  Projects/SoulBound_Confession/images/slider-02.jpg
  Projects/SoulBound_Confession/images/slider-03.jpg
  Projects/SoulBound_Confession/images/tag-line.png
  Projects/SoulBound_Confession/index.html
  Projects/SoulBound_Confession/js/images-loded.min.js
  Projects/SoulBound_Confession/js/jquery.min.js
  Projects/SoulBound_Confession/js/jquery.pogo-slider.min.js
  Projects/SoulBound_Confession/js/main.js
  Projects/SoulBound_Confession/js/responsiveslides.min.js
  Projects/SoulBound_Confession/js/slider-index.js
Labels: Approved, Ready to merge, SSOC 2.0

#1867 Readme file for A responsive movie website
  Projects/A responsive movie website/Readme.md
Labels: Approved, Ready to merge, SSOC 2.0

#1750 Finance
  Projects/Finance Tracker/Readme.md
  Projects/Finance Tracker/index.html
  Projects/Finance Tracker/index.js
  Projects/Finance Tracker/styles.css
Labels: Approved, Ready to merge, SSOC 2.0

#1767 Home Page of Newsletter Website
  Projects/Newsletter-Website/images/bhopal.webp
  Projects/Newsletter-Website/images/cyclone.webp
  Projects/Newsletter-Website/images/dam.jpg
  Projects/Newsletter-Website/images/delhi-cover.jpg
  Projects/Newsletter-Website/images/rahul-gandhi.webp
  Projects/Newsletter-Website/images/search-icon.png
  Projects/Newsletter-Website/images/vlogger.jpg
  Projects/Newsletter-Website/index.html
  Projects/Newsletter-Website/styles.css
  Projects/Spotify Clone/s_index.html
  Projects/Spotify Clone/s_script.js
  Projects/Spotify Clone/s_style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1774 add pagination
  Projects/Recipe Finder/assets/script.js
  Projects/Recipe Finder/assets/style.css
  Projects/Recipe Finder/index.html
Labels: Approved, Ready to merge, SSOC 2.0

#1786 Loan Calculator Modified
  Projects/Loan-calculator/loancalculator.js
Labels: Approved, Ready to merge, SSOC 2.0

#1791 Added Alarm Setter Website
  Projects/Alarm Setter/Readme.md
  Projects/Alarm Setter/files/clock.svg
  Projects/Alarm Setter/files/ringtone.mp3
  Projects/Alarm Setter/image.png
  Projects/Alarm Setter/index.html
  Projects/Alarm Setter/script.js
  Projects/Alarm Setter/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1805 feat: add github action to lock new issues
  .github/workflows/lock-issues.yml
Labels: Approved, Ready to merge, SSOC 2.0

#1811 now clears the resume as well
  Projects/Resume Creator/app.js
  Projects/Resume Creator/index.html
Labels: Approved, Ready to merge, SSOC 2.0

#1812 now looks visible
  Projects/HuffmanCompressor/index.html
  Projects/HuffmanCompressor/styles.css
Labels: Approved, Ready to merge, SSOC 2.0

#1813 To add Text effect to the title
  Projects/Digital Clock/index.html
  Projects/Digital Clock/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1814 feat: add pre-loader animation
  index.html
  style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1815 Added Essentia - NEW PROJECT
  Projects/Essentia/README.md
  Projects/Essentia/images/android-chrome-192x192.png
  Projects/Essentia/images/android-chrome-512x512.png
  Projects/Essentia/images/apple-touch-icon.png
  Projects/Essentia/images/favicon-16x16.png
  Projects/Essentia/images/favicon-32x32.png
  Projects/Essentia/images/favicon.ico
  Projects/Essentia/images/home.png
  Projects/Essentia/images/img.png
  Projects/Essentia/images/item1.png
  Projects/Essentia/images/item2.png
  Projects/Essentia/images/item3.png
  Projects/Essentia/images/item4.png
  Projects/Essentia/index.html
  Projects/Essentia/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1825 Please merge my PR for Amazon-Clone
  Amazon-Clone-main/README.md
  Amazon-Clone-main/index.html
  Amazon-Clone-main/javascript.js
  Amazon-Clone-main/style.css
  Amazon-Clone-main/todayDeal.js
Labels: Approved, Ready to merge, SSOC 2.0

#1827 Animated wallpaper project(new project) please verify and merge
  Projects/Animated-Wallpaper/README.md
  Projects/Animated-Wallpaper/colourfull.png
  Projects/Animated-Wallpaper/index.html
  Projects/Animated-Wallpaper/oranges.jpg
  Projects/Animated-Wallpaper/script.js
  Projects/Animated-Wallpaper/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1831 armstrong checker modified
  Projects/ArmstrongChecker/armstrong.js
Labels: Approved, Ready to merge, SSOC 2.0

#1836 Coin Flip Game added [SSoC'23] issue #1785
  Projects/Coin Flip game/README.md
  Projects/Coin Flip game/assets/head.png
  Projects/Coin Flip game/assets/img1.png
  Projects/Coin Flip game/assets/img2.png
  Projects/Coin Flip game/assets/img3.png
  Projects/Coin Flip game/assets/img4.jpg
  Projects/Coin Flip game/assets/tail.png
  Projects/Coin Flip game/index.html
  Projects/Coin Flip game/index.js
  Projects/Coin Flip game/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1845 improved the inputs and the buttons ui
  Projects/Corona-Tracker/index.css
Labels: Approved, Ready to merge, SSOC 2.0

#1846 add the required padding
  Projects/Bookmarker_App/index.html
Labels: Approved, Ready to merge, SSOC 2.0

#1855 bringing calculator and heading block at center of the page
  Projects/Age Calculator/index.html
  Projects/Age Calculator/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1858 Fake Store
  Projects/Fake Store/Images/Screenshot 2023-07-27 184625.png
  Projects/Fake Store/Images/Screenshot 2023-07-27 184702.png
  Projects/Fake Store/Images/Screenshot 2023-07-27 184720.png
  Projects/Fake Store/Images/Screenshot 2023-07-27 184733.png
  Projects/Fake Store/Images/Screenshot 2023-07-27 184742.png
  Projects/Fake Store/Images/Screenshot 2023-07-27 184753.png
  Projects/Fake Store/Images/Screenshot 2023-07-27 184810.png
  Projects/Fake Store/index.html
  Projects/Fake Store/readme.md
  Projects/Fake Store/script.js
  Projects/Fake Store/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1800 Hotstar Clone[SSOC'23]
  Projects/Hotsar Clone/Images Hotstar/add.png
  Projects/Hotsar Clone/Images Hotstar/disney.PNG
  Projects/Hotsar Clone/Images Hotstar/geographic.PNG
  Projects/Hotsar Clone/Images Hotstar/logo.png
  Projects/Hotsar Clone/Images Hotstar/marvel.PNG
  Projects/Hotsar Clone/Images Hotstar/nxt.png
  Projects/Hotsar Clone/Images Hotstar/pixar.PNG
  Projects/Hotsar Clone/Images Hotstar/play.png
  Projects/Hotsar Clone/Images Hotstar/poster 1.png
  Projects/Hotsar Clone/Images Hotstar/poster 10.png
  Projects/Hotsar Clone/Images Hotstar/poster 11.png
  Projects/Hotsar Clone/Images Hotstar/poster 12.png
  Projects/Hotsar Clone/Images Hotstar/poster 2.png
  Projects/Hotsar Clone/Images Hotstar/poster 3.png
  Projects/Hotsar Clone/Images Hotstar/poster 4.png
  Projects/Hotsar Clone/Images Hotstar/poster 5.png
  Projects/Hotsar Clone/Images Hotstar/poster 6.png
  Projects/Hotsar Clone/Images Hotstar/poster 7.png
  Projects/Hotsar Clone/Images Hotstar/poster 8.png
  Projects/Hotsar Clone/Images Hotstar/poster 9.png
  Projects/Hotsar Clone/Images Hotstar/pre.png
  Projects/Hotsar Clone/Images Hotstar/slider 1.PNG
  Projects/Hotsar Clone/Images Hotstar/slider 2.PNG
  Projects/Hotsar Clone/Images Hotstar/slider 3.PNG
  Projects/Hotsar Clone/Images Hotstar/slider 4.PNG
  Projects/Hotsar Clone/Images Hotstar/slider 5.PNG
  Projects/Hotsar Clone/Images Hotstar/star-wars.PNG
  Projects/Hotsar Clone/Index.html
  Projects/Hotsar Clone/README.md
  Projects/Hotsar Clone/Videos Hotstar/disney.mp4
  Projects/Hotsar Clone/Videos Hotstar/geographic.mp4
  Projects/Hotsar Clone/Videos Hotstar/marvel.mp4
  Projects/Hotsar Clone/Videos Hotstar/pixar.mp4
  Projects/Hotsar Clone/Videos Hotstar/star-war.mp4
  Projects/Hotsar Clone/index.js
  Projects/Hotsar Clone/styles.css
Labels: Approved, Ready to merge, SSOC 2.0

#1892 Age calculator
  Projects/Age Calculator/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1879 Update Readme
  CONTRIBUTING.md
Labels: Approved, Ready to merge, SSOC 2.0

#1888 Amazon clone
  Projects/Amazonclone/amazon_logo.png
  Projects/Amazonclone/box1_image.jpg
  Projects/Amazonclone/box2_image.jpg
  Projects/Amazonclone/box3_image.jpg
  Projects/Amazonclone/box4_image.jpg
  Projects/Amazonclone/box5_image.jpg
  Projects/Amazonclone/box6_image.jpg
  Projects/Amazonclone/box7_image.jpg
  Projects/Amazonclone/box8_image.jpg
  Projects/Amazonclone/hero_image.jpg
  Projects/Amazonclone/index.html
  Projects/Amazonclone/style.css
Labels: Approved, Ready to merge, SSOC 2.0

#1891 [SSOC 2.0] Readme File for Analog Clock
  Projects/Analog Clock/readme.md
Labels: Approved, Ready to merge, SSOC 2.0

#1872 fitness website [new project]
  Projects/Fitness-website/img/bells.jpg
  Projects/Fitness-website/img/chris-heria.jpg
  Projects/Fitness-website/img/chris.jpg
  Projects/Fitness-website/img/cycle.jpg
  Projects/Fitness-website/img/github.png
  Projects/Fitness-website/img/loupe.png
  Projects/Fitness-website/img/men-yoga.jpg
  Projects/Fitness-website/img/pullup.jpg
  Projects/Fitness-website/img/resist.jpg
  Projects/Fitness-website/img/resistband.jpg
  Projects/Fitness-website/img/swimming.jpg
  Projects/Fitness-website/img/treadmill.jpg
  Projects/Fitness-website/img/walk.jpg
  Projects/Fitness-website/img/weight-lifting-1284616_1920.jpg
  Projects/Fitness-website/img/yg.jpg
  Projects/Fitness-website/index.html
  Projects/Fitness-website/slider.js
  Projects/Fitness-website/styles.css
  img/projects/website.jpg
  projects.js
  script.js
Labels: Approved, Ready to merge, SSOC 2.0

#1904 Added some functions for double move
  Projects/chess/code.js
Labels: Approved, Ready to merge, SSOC 2.0

#1910 [SSoC'23] World Clock project added
  Projects/World Clock/README.md
  Projects/World Clock/assets/img1.png
  Projects/World Clock/assets/img2.png
  Projects/World Clock/assets/img3.png
  Projects/World Clock/assets/img4.png
  Projects/World Clock/index.html
  Projects/World Clock/script.js
  Projects/World Clock/style.css
Labels: Approved, Ready to merge, SSOC 2.0
